version: "3.8"
services:
  backend:
    image: python:3.9-slim
    volumes:
      - /mnt/HKS/Apps/GM-Vehicles/backend:/app
    working_dir: /app
    command: gunicorn -w 4 -b 0.0.0.0:5000 start:app --preload
    networks:
      - app-network

  frontend:
    image: node:14
    volumes:
      - /mnt/HKS/Apps/GM-Vehicles/frontend:/app
    working_dir: /app
    command: node server.js
    networks:
      - app-network

  nginx:
    image: nginx:stable
    volumes:
      - /mnt/HKS/Apps/GM-Vehicles/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /mnt/HKS/Apps/GM-Vehicles/certbot/conf:/etc/letsencrypt
      - /mnt/HKS/Apps/GM-Vehicles/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /mnt/HKS/Apps/GM-Vehicles/certbot/conf:/etc/letsencrypt
      - /mnt/HKS/Apps/GM-Vehicles/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; certbot renew --webroot -w /var/www/certbot; done'"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
