version: "3.8"

networks:
  app-network:
    driver: bridge

services:
  frontend:
    build: ./frontend
    restart: always
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build: ./backend
    restart: always
    env_file:
      - stack.env
    networks:
      - app-network

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot  # For Let's Encrypt SSL
      - ./certbot/conf:/etc/letsencrypt # For SSL certificates
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  mysql_data:
