version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - app-network
      - frontend-macvlan

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  frontend-macvlan:
    driver: macvlan
    driver_opts:
      parent: ens6f1
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.254
          ip_range: 192.168.1.200/29
