version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - frontend-macvlan
        ipv4_address: 192.168.1.1
      - app-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  frontend-macvlan:
    external: true
