version: "3.8"
services:
  backend:
    build: ./backend
    networks:
      - app-network
    env_file: ./.env
    restart: always

  frontend:
    build: ./frontend
    networks:
      - app-network
    restart: always

  nginx:
    image: nginx:stable
    networks:
      front-macvlan:
        ipv4_address: 192.168.1.50
      app-network: {}
    volumes:
      - /mnt/HKS/Apps/GM-Vehicles/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /mnt/HKS/Apps/GM-Vehicles/certbot/conf:/etc/letsencrypt
      - /mnt/HKS/Apps/GM-Vehicles/certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /mnt/HKS/Apps/GM-Vehicles/certbot/conf:/etc/letsencrypt
      - /mnt/HKS/Apps/GM-Vehicles/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; certbot renew --webroot -w /var/www/certbot; done'"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  front-macvlan:
    external: true
