const colorMap = {
  "ROSWELL GREEN METALLIC": "G4Z",
  "BAEGE METALLIC": "BAEGE METALLIC",
  "COPPERTINO METALLIC": "COPPERTINO METALLIC",
  "ABALONE WHITE": "ABALONE WHITE",
  "SEYCHELLES METALLIC": "SEYCHELLES METALLIC",
  "SEEKER METALLIC": "SEEKER METALLIC",
  "KIMONO METALLIC": "KIMONO METALLIC",
  "CHARTREUSE METALLIC": "CHARTREUSE METALLIC",
  "CHARTREUSE MATTE": "CHARTREUSE MATTE",
  "HIGH VOLTAGE TINT": "HIGH VOLTAGE TINT",
  "TACTICAL TINT": "TACTICAL TINT",
  "HYPERSONIC METALLIC": "HYPERSONIC METALLIC",
  "BARB WIRE": "BARB WIRE",
  "BLACK MEETS KETTLE": "BLACK MEETS KETTLE",
  "ACCELERATE YELLOW METALLIC": "GD0",
  "AMPLIFY ORANGE TINTCOAT": "GC5",
  "CORVETTE RACING YELLOW TINTCOAT": "GC6",
  "ARCTIC WHITE": "G8G",
  "ARGENT SILVER METALLIC": "GXD",
  "BLACK DIAMOND TRICOAT": "GLK",
  "BLACK RAVEN": "GBA",
  "BLACK": "GBA",
  "BLADE SILVER METALLIC": "GAN",
  "BLAZE ORANGE METALLIC": "GCF",
  "CACTI GREEN": "GVR",
  "CAFFEINE METALLIC": "G48",
  "CARBON FLASH METALLIC": "GAR",
  "CERAMIC MATRIX GRAY METALLIC": "G9F",
  "COASTAL BLUE METALLIC": "GJV",
  "COMPETITION YELLOW TINTCOAT": "GBK",
  "CRUSH": "G16",
  "CRYSTAL WHITE TRICOAT": "G1W",
  "CYBER YELLOW METALLIC": "GCP",
  "DARK EMERALD FROST": "G7W",
  "DARK MOON METALLIC": "GLU",
  "DEEP SPACE METALLIC": "GAI",
  "ELECTRIC BLUE": "GMO",
  "ELKHART LAKE BLUE METALLIC": "GS7",
  "EVERGREEN METALLIC": "GJ0",
  "GARNET METALLIC": "GLR",
  "GARNET RED TINTCOAT": "G7E",
  "HYPERSONIC GRAY METALLIC": "GA7",
  "HYSTERIA PURPLE METALLIC": "GXL",
  "INFRARED TINTCOAT": "GSK",
  "LONG BEACH RED METALLIC TINTCOAT": "G1E",
  "MANHATTAN NOIR METALLIC": "GCI",
  "MAVERICK NOIR FROST": "GNW",
  "MERCURY SILVER METALLIC": "GKA",
  "MIDNIGHT SKY METALLIC": "GXF",
  "MIDNIGHT STEEL METALLIC": "GXU",
  "NITRO YELLOW METALLIC": "GCP",
  "PANTHER BLACK MATTE": "GNW",
  "PANTHER BLACK METALLIC TINTCOAT": "GLK",
  "RADIANT RED TINTCOAT": "GNT",
  "RADIANT SILVER METALLIC": "GAN",
  "RALLY GREEN METALLIC": "GJ0",
  "RAPID BLUE": "GMO",
  "RED HORIZON TINTCOAT": "GPJ",
  "RED HOT": "G7C",
  "RED MIST METALLIC TINTCOAT": "GPH",
  "RED OBSESSION TINTCOAT": "G7E",
  "RIFT METALLIC": "GRW",
  "RIPTIDE BLUE METALLIC": "GJV",
  "RIVERSIDE BLUE METALLIC": "GKK",
  "ROYAL SPICE METALLIC": "GLL",
  "SATIN STEEL GRAY METALLIC": "G9K",
  "SATIN STEEL METALLIC": "G9K",
  "SEA WOLF GRAY TRICOAT": "GXA",
  "SEBRING ORANGE TINTCOAT": "G26",
  "SHADOW GRAY METALLIC": "GJI",
  "SHADOW METALLIC": "GJI",
  "SHARKSKIN METALLIC": "GXD",
  "SHOCK": "GKO",
  "SILVER FLARE METALLIC": "GSJ",
  "STELLAR BLACK METALLIC": "GB8",
  "SUMMIT WHITE": "GAZ",
  "TORCH RED": "GKZ",
  "TYPHOON METALLIC": "GBW",
  "VELOCITY RED": "G7C",
  "VIVID ORANGE METALLIC": "GCF",
  "WAVE METALLIC": "GKK",
  "WHITE PEARL METALLIC TRICOAT": "G1W",
  "WILD CHERRY TINTCOAT": "GSK",
  "ZEUS BRONZE METALLIC": "GUI",
  "SILVER ICE METALLIC": "GAN",
  "MOSAIC BLACK METALLIC": "GB8",
  "WATKINS GLEN GRAY METALLIC": "G7Q",
  "ADMIRAL BLUE METALLIC": "GTR",
  "INTERSTELLAR WHITE": "GAZ",
  "VOID BLACK": "GBA",
  "METEORITE METALLIC": "GNO",
  "DEEP AURORA METALLIC": "GXN",
  "AFTERBURNER TINTCOAT": "GC5",
  "TIDE METALLIC": "G7X",
  "SUPERNOVA METALLIC": "GKK",
  "NEPTUNE BLUE MATTE": "GLG",
  "SOLAR ORANGE": "GAG",
  "GRAPHITE BLUE METALLIC": "GAI",
  "MOONSHOT GREEN MATTE": "G7W",
  "COASTAL DUNE": "G42",
  "MAGNUS GRAY MATTE": "GBL",
  "AUBURN MATTE": "GNR",
  "BLUE SMOKE METALLIC": "GAI",
  "SLATE GRAY METALLIC": "GNO",
  "HABANERO ORANGE": "GAG",
  "ZEPHYR BLUE MATTE METALLIC": "GLG",
  "DARK EMBER TINTCOAT": "GAB",
  "DEEP OCEAN METALLIC": "GAI",
  "ONYX BLACK": "GBA",
  "MOONLIGHT MATTE": "GLG",
  "GLACIER WHITE TRICOAT": "G4J",
  "DEEP BRONZE METALLIC": "GXN",
  "THUNDERSTORM GRAY": "GNO",
  "SANDSTONE": "G42",
  "VIBRANT WHITE TRICOAT": "G4J",
  "BLACK CHERRY TINTCOAT": "GAB",
  "MONARCH ORANGE": "GAG",
  "MAGNUS METAL FROST": "GBL",
  "LUNA METALLIC": "GNO",
  "ADOBE FROST": "GNR",
  "FLARE METALLIC": "GSJ",
  "MIDNIGHT STEEL FROST": "GLG",
};

const intColor = {
  // Corvette
  // - C7
  "141": "Gray Perforated Mulan Leather",
  "143": "Gray Perforated Mulan Leather",
  "144": "Gray Leather w/ Sueded Microfiber Inserts",
  "145": "Gray Perforated Napa Leather",
  "146": "Gray Leather w/ Sueded Microfiber Inserts",
  "191": "Jet Black Perforated Mulan Leather",
  "192": "Jet Black Leather w/ Sueded Microfiber Inserts",
  "193": "Jet Black Perforated Mulan Leather",
  "194": "Jet Black Leather w/ Sueded Microfiber Inserts",
  "195": "Jet Black Perforated Napa Leather",
  "196": "Jet Black Leather w/ Sueded Microfiber Inserts",
  "198": "Jet Black Leather w/ Sueded Microfiber Inserts",
  "343": "Kalahari Perforated Mulan Leather",
  "344": "Kalahari Leather w/ Sueded Microfiber Inserts",
  "345": "Kalahari Perforated Napa Leather",
  "346": "Kalahari Leather w/ Sueded Microfiber Inserts",
  "701": "Adrenaline Red Perforated Mulan Leather",
  "703": "Adrenaline Red Perforated Mulan Leather",
  "704": "Adrenaline Red Leather w/ Sueded Microfiber Inserts",
  "705": "Adrenaline Red Perforated Napa Leather",
  "706": "Adrenaline Red Leather w/ Sueded Microfiber Inserts",
  "755": "Spice Red Perforated Mulan Leather",
  "000": "Jet Black w/ Orange Stitching Leather w/ Sueded Microfiber Inserts",
  // - C8
  "HTA": "Jet Black Mulan Leather w/ Perforated Inserts",
  "HTE": "Jet Black Napa Leather w/ Perforated Inserts",
  "HTJ": "Jet Black Performance Textile",
  "HTO": "Tension W/ Twilight Blue Dipped Napa Leather w/ Perforated Inserts",
  "HU1": "Sky Cool Gray Napa Leather w/ Perforated Inserts",
  "HU2": "Adrenaline Red Napa Leather w/ Perforated Inserts",
  "HU3": "Morello Red Dipped Napa Leather w/ Perforated Inserts",
  "HUE": "Natural Napa Leather w/ Perforated Inserts",
  "HUP": "Sky Cool Gray Mulan Leather w/ Perforated Inserts",
  "HUQ": "Adrernaline Red Mulan Leather w/ Perforated Inserts",
  "HUR": "Adrernaline Red Mulan Leather w/ Perforated Inserts",
  "HUL": "Adrernaline Red NAPA Leather w/ Perforated Inserts",
  "HU7": "Adrernaline Red NAPA Leather w/ Perforated SUEDED MICROFIBER Inserts",
  "HUA": "Adrernaline Red NAPA Leather w/ Perforated SUEDED MICROFIBER Inserts",
  "HZN": "Natural Dipped Napa Leather w/ Perforated Inserts",
  "HTM": "JET BLACK NAPA LEATHER W/ PERFORATED INSERTS",
  "HTP": "JET BLACK NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  "HTT": "JET BLACK NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  "HUN": "SKY COOL GRAY MULAN LEATHER W/ PERFORATED INSERTS",
  "HUK": "SKY COOL GRAY NAPA LEATHER W/ PERFORATED INSERTS",
  "HU6": "SKY COOL GRAY NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  "HU9": "SKY COOL GRAY NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  "HUV": "NATURAL MULAN LEATHER W/ PERFORATED INSERTS",
  "HTN": "NATURAL NAPA LEATHER W/ PERFORATED INSERTS",
  "HTQ": "NATURAL NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  "HTG": "NATURAL NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  "HUF": "NATURAL DIPPED NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  "HT7": "SKY COOL GRAY W/ STRIKE YELLOW NAPA LEATHER W/ PERFORATED INSERTS",
  "HFC": "SKY COOL GRAY W/ STRIKE YELLOW NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  "HNK": "ADDRENALINE RED DIPPED NAPA LEATHER W/ PERFORATED INSERTS",
  "HV1": "CERAMIC WHITE W/ RED STITCHING NAPA LEATHER W/ PERFORATED INSERTS",
  "HV2": "ARTEMIS NAPA LEATHER W/ PERFORATED INSERTS",
  "HUX": "HABANERO NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  "HUW": "HABANERO NAPA LEATHER W/ PERFORATED INSERTS",
  "HZB": "CUSTOM SKY COOL GRAY W/ JET BLACK ACCENTS NAPA LEATHER W/ PERFORATED INSERTS",
  "HVT": "CUSTOM SKY COOL GRAY W/ JET BLACK ACCENTS NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  "HVV": "CUSTOM JET BLACK W/ SKY COOL GRAY ACCENTS NAPA LEATHER W/ PERFORATED INSERTS",
  "HMO": "CUSTOM JET BLACK W/ SKY COOL GRAY ACCENTS NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  "HUU": "CUSTOM ADRENALINE RED W/ JET BLACK ACCENTS NAPA LEATHER W/ PERFORATED INSERTS",
  "HZP": "CUSTOM ADRENALINE RED W/ JET BLACK ACCENTS NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  "HU0": "CUSTOM JET BLACK W/ ADRENALINE RED ACCENTS NAPA LEATHER W/ PERFORATED INSERTS",
  "HXO": "CUSTOM JET BLACK W/ ADRENALINE RED ACCENTS NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  // Camaro
  "H01": "Kalahari Leather",
  "H0W": "Jet Black Leather W/ Red accents",
  "H0Y": "Jet Black Leather",
  "H13": "Ceramic White Leather",
  "H16": "Adrenaline Red Leather",
  "H17": "Medium Ash Gray Leather",
  "H1T": "Jet Black Cloth",
  "H72": "Medium Ash Gray Cloth",
  // Cadillac
  "E2B": "Jet Black W/ Signet Accents Leather w/ Mini-Perforated Custom Quilted Inserts and Sueded Front Seatbacks",
  "E2D": "Jet Black W/ Adrenaline Red Accents Leather w/ Mini-Perforated Custom Quilted Inserts and Sueded Front Seatbacks",
  "E2G": "Jet Black W/ Sky Cool Gray Accents Leather w/ Mini-Perforated Custom Quilted Inserts and Sueded Front Seatbacks",
  "H0L": "Sangria W/ Jet Black Accents Leather w/ Mini-Perforated Inserts",
  "H0M": "Cinnamon W/ Jet Black Accents Leather w/ Mini-Perforated Inserts",
  "H1Y": "Jet Black W/ Jet Black Accents Leather w/ Mini-Perforated Inserts",
  "H2G": "Jet Black W/ Jet Black Accents Inteluxe",
  // UNSURE "H2X": "JET BLACK LEATHER W/ CHEVRON PERFORATED INSERTS",
  "H2X": "Jet Black W/ Jet Black Accents Leather w/ Mini-Perforated Inserts",
  "H66": "JET BLACK LEATHER",
  "HAV": "Maple Sugar W/ Jet Black Accents Leather w/ Mini-Perforated Inserts",
  "HBE": "Jet Black W/ Jet Black Accents Leather/Performance Cloth/Sueded Microfiber/Ineluxe and Sueded Front Seatbacks",
  "HBF": "Natural Tan W/ Jet Black Accents Leather w/ Mini-Perforated Custom Quilted Inserts and Sueded Front Seatbacks",
  "HEA": "Jet Black W/ Jet Black Accents Leather w/ Sueded Front Seatbacks",
  "HEB": "Sky Cool Gray W/ Jet Black Accents Leather w/ Sueded Front Seatbacks",
  "HGM": "Jet Black W/ Jet Black Accents Leather w/ Mini-Perforated Inserts",
  "HIK": "Sahara Beige W/ Jet Black Accents Leather w/ Mini-Perforated Inserts",
  "HIT": "Sahara Beige W/ Jet Black Accents Inteluxe",
  "HIZ": "SEMI-ANILINE LEATHER W/ CHEVRON PERFORATED INSERTS",
  "HJC": "Natural Tan W/ Jet Black Accents Full Semi-Aniline Leather w/ Mini-Perforated Inserts: Custom Quilting and Carbon Fiber Front Seatbacks",
  "HJD": "Sky Cool Gray W/ Jet Black Accents Full Semi-Aniline Leather w/ Mini-Perforated Inserts: Custom Quilting and Carbon Fiber Front Seatbacks",
  "HK1": "VERY LIGHT CASHMERE W/ MAPLE SUGAR ACCENTS SEMI-ANILINE LEATHER W/ CHEVRON PERFORATED INSERTS",
  "HMC": "Whisper Beige W/ Jet Black Accents Inteluxe",
  "HMQ": "SAHARA BEIGE W/ JET BLACK ACCENTS LEATHER W/ CHEVRON PERFORATED INSERTS",
  "HMR": "Jet Black W/ Jet Black Accents Full Semi-Aniline Leather w/ Mini-Perforated Inserts: Custom Quilting and Carbon Fiber Front Seatbacks",
  "HNC": "Whisper Beige W/ Jet Black Accents Leather w/ Mini-Perforated Inserts",
  "HND": "Whisper Beige W/ Jet Black Accents Leather w/ Mini-Perforated Inserts",
  "HTX": "DARK AUBURN W/ JET BLACK ACCENTS LEATHER W/ CHEVRON PERFORATED INSERTS",
  "HTZ": "SAHARA BEIGE W/ JET BLACK ACCENTS LEATHER",
  "HXR": "Jet Black W/ Jet Black Accents Inteluxe",
  "HZK": "Sedona Sauvage W/ Jet Black Accents Semi-Aniline Full Leather w/ Chevron Perforated Inserts",
  "HZQ": "Jet Black W/ Jet Black Accents Inteluxe",
  "EG1": "Sky Cool Gray W/ Santorini Blue Accents Leather W/ Mini-Perforated Custom Quilted Inserts and Sueded Front Seatbacks",
  "E54": "Jet Black W/ Phantom Blue Accents Leather W/ Mini-Perforated Custom Quilted Inserts and Sueded Front Seatbacks",
  "H9F": "Jet Black Evotex",
  "EMX": "Black Evotex",
  // ESCALADE IQ
  "ENB": "SHEER GRAY W/ DARK MEDIUM CINDER ACCENTS INTELUXE W/ FJORD (CHEVRON) QUILTING PATTERN",
  "EMY": "CAMELIA W/ BACKEN BLACK ACCENTS NOUVEAULUXE W/ EVREN (BACK INSERTS) AND CYGUS (SEAT CUSHION) PERFORATED PATTERN",
  "ENK": "HARBOR BLUE W/ BACKEN BLACK ACCENTS NOUVEAULUXE W/ CARRINGTON FALLS PERFORATED PATTERN",
  // Hummer EV
  "H9Z": "LUNAR HORIZON (JET BLACK/LIGHT GREY) Premium Leather-Alternative",
  "HAS": "LUNAR SHADOW (JET BLACK/TAUPE) Premium Leather-Alternative",
  "HBZ": "GRANITE DRIFT PREMIUM LEATHER-ALTERNATIVE",
  "HR5": "STEALTH ECLIPSE PREMIUM LEATHER-ALTERNATIVE",
  "EHM": "VELOCITY EMBER PREMIUM LEATHER-ALTERNATIVE",
  // Silverado EV
  "H7D": "Black Evotex",
  //"H7D": "BACKEN BLACK W/ SANTORINI ACCENTS INTELUXE W/ FJORD (CHEVRON) QUILTING PATTERN", ESCALADE IQ
  "EMW": "Black w/ Sky Cool Gray Evotex",
  // Sierra EV
  "E4V": "After Dark (Black) Premium Leather alternative",
  "EWA": "Desert Dune Premium Leather alternative",
  "EH7": "AFTER DARK (BLACK) CORETEC",
  "EH9": "FOREST STORM CORETEC",
  "HCN": "Black Evotex",
  "EB9": "Black w/ Artemis Evotex",
};

const seatCode = {
  // Camaro
  "A50": "Sport front buckets",
  "AQJ": "RECARO Performance front buckets",
  // Corvette
  "AQ9": "GT1 buckets",
  "AE4": "Competition buckets",
  "AH2": "GT2 / Competition buckets",
  // Cadillac
  "": "",
  // Silverado EV
  "AR9": "Front Bucket Seats",
  // Hummer EV
  "A50": "Front bucket seats with center console",
};

const mmc = {
  // Camaro
  "1AG37": "1LT",
  "1AG67": "1LT",
  "1AH37": "2LT",
  "1AH67": "2LT",
  "1AJ37": "1SS",
  "1AJ67": "1SS",
  "1AK37": "2SS",
  "1AK67": "2SS",
  "1AL37": "1SE",
  "1AL67": "1SE",
  // Corvette SR C7
  "1YY07": "", // Coupe
  "1YY67": "", // Conv
  // Corvette GS C7
  "1YW07": "", // Coupe
  "1YW67": "", // Conv
  // Corvette SR Z51 C7
  "1YX07": "", // Coupe
  "1YX67": "", // Conv
  // Corvette Z06 C7
  "1YZ07": "", // Coupe
  "1YZ67": "", // Conv
  // Corvette ZR1 C7
  "1YV07": "", // Coupe
  "1YV67": "", // Conv
  // Corvette C8
  "1YC07": "", // Coupe
  "1YC67": "", // Conv
  // Corvette Z06 C8
  "1YH07": "", // Coupe
  "1YH67": "", // Conv
  // Corvette E-Ray C8
  "1YG07": "", // Coupe
  "1YG67": "", // Conv
  // Corvette ZR1 C8
  "1YR07": "", // Coupe
  "1YR67": "", // Conv
  // Cadillac
  "6DB69": "1SB", // CT4 LUXURY
  "6DB79": "1SB", // CT5 LUXURY
  "6DC69": "1SD", // CT4 PREMIUM LUXURY
  "6DC79": "1SD", // CT5 PREMIUM LUXURY
  "6DD69": "1SE", // CT4 SPORT
  "6DD79": "1SE", // CT5 SPORT
  "6DE69": "1SF", // CT4 V-SERIES
  "6DE79": "1SF", // CT5 V-SERIES
  "6DF69": "1SP", // CT4 V-SERIES BLACKWING
  "6DF79": "1SV", // CT5 V-SERIES BLACKWING
  "6KM69": "1SP", // CT6 PLATINUM
  "6KH69": "1SB", // CT6 LUXURY
  "6KJ69": "1SD", // CT6 PREMIUM LUXURY
  "6KN69": "1SV", // CT6 V-SERIES
  // Hummer EV
  "TT35526": "", // SUV
  "TT35743": "", // Pickup
  // Silverado EV
  "CT35843": "",
  // Sierra EV
  "TT35843": "",
};

const camaroRpo = {
  "00Y": "Not Equipped with Rear Park Assist, see dealer for details",
  "19T": "Convertible top color, Black",
  "2F5": "Knee pads, Red",
  "3DL": "Interior trim, carbon fiber instrument panel molding",
  "3F9": "Seat belt color, Red",
  "56H": "LPO, SS 20\" (50.8 cm) 5-spoke gloss Black wheels with Red stripe",
  "56H": "LPO, 20\" (50.8 cm) 5-spoke gloss Black wheels with Red outline stripe",
  "56K": "LPO, SS 20\" (50.8 cm) 5-split spoke polished forged wheels with Black star center cap",
  "56K": "LPO, 20\" (50.8 cm) polished forged wheels with Black star center cap",
  "56M": "LPO, SS 20\" (50.8 cm) 5-split spoke machined-face wheels",
  "56M": "LPO, 20\" (50.8 cm) 5-split spoke machined-face wheels",
  "56R": "Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear 5-split spoke premium Gray-painted machined-face aluminum",
  "56S": "Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear bright 5-spoke Silver-painted aluminum",
  "56S": "Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear bright 5- spoke Silver-painted aluminum",
  "56V": "Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear 5-spoke Carbon Flash painted aluminum",
  "56W": "Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear 5-spilt spoke bright Silver-painted aluminum",
  "56Y": "Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear blade design aluminum",
  "56Z": "Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear 5-split spoke Black forged aluminum",
  "56Z": "Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear low gloss Black-painted forged aluminum",
  "57S": "LPO, SS 20\" (50.8 cm) 5-split spoke Satin Black wheels",
  "57V": "Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear Caliente",
  "57W": "Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear 5-split spoke polished forged aluminum with Black star center cap",
  "57W": "Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear 5-split spoke polished forged with Black star center cap",
  "58E": "Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear Black-painted aluminum with Red accents",
  "58E": "Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear Black- painted aluminum with Red accents",
  "5JW": "LPO, 20\" (50.8 cm) 5-split spoke polished forged wheels with Black star center cap",
  "5JW": "LPO, 20\" (50.8 cm) polished forged wheels with Black star center cap",
  "5JX": "LPO, LT 20\" (50.8 cm) 5-split spoke Satin Black wheels",
  "5K2": "LPO, Decklid blackout decal",
  "5K9": "Wheels, 20\" (50.8 cm) Caliente",
  "5KP": "LPO, Illuminated sill plates",
  "5LQ": "LPO, 6 Piston Front Brake Kit",
  "5V5": "LPO, Body-color high-wing spoiler",
  "5V5": "LPO, Body-color wing spoiler",
  "5V6": "LPO, Black Interior Appearance Package",
  "5VF": "LPO, Carbon fiber exhaust tip",
  "5VM": "LPO, Ground Effects Package",
  "5WF": "LPO, Battery Protection Package",
  "5YN": "LPO, Carbon Fiber-look shift knob (auto) or Carbon Fiber-look shift knob medallion (manual)",
  "5ZB": "LPO, Camaro logo wheel center caps",
  "5ZD": "LPO, Wheel center caps",
  "5ZU": "LPO, Body-color blade spoiler",
  "5ZV": "LPO, Satin Black blade spoiler",
  "5ZW": "LPO, Satin Black wing spoiler",
  "5ZZ": "LPO, Carbon Flash Metallic blade spoiler",
  "62F": "LPO, Premium carpeted cargo mat with Camaro logo",
  "62O": "LPO, Clear CHMSL (Center High Mount Stop Lamp)",
  "6ZQ": "LPO, ZL1 1LE SPEC visible carbon fiber spoiler",
  "A1X": "1LE Track Performance Package",
  "A1Y": "SS 1LE Track Performance Package",
  "A1Z": "ZL1 1LE Extreme Track Performance Package",
  "A45": "Memory Package",
  "A50": "Seats, front Sport bucket",
  "A62": "Seat, rear fixed",
  "A9B": "Satin Black Appearance Package",
  "AAQ": "Seat adjuster, front passenger",
  "AJ7": "Airbags, frontal and side-impact, driver and passenger",
  "AJ9": "Airbags, dual-stage frontal, knee, head and thorax side-impact, driver and front passenger",
  "AKQ": "Seat adjuster, front passenger, 6-way power",
  "AM7": "Seat, rear, folding",
  "AQJ": "Seats, front bucket, RECARO performance",
  "ATH": "Keyless Open and Start",
  "AV3": "Seat adjuster, driver, 8-way power",
  "AYG": "Airbags, dual-stage frontal, thorax side-impact and knee, driver and front passenger, and head curtain side-impact",
  "B2E": "Shock and Steel Special Edition",
  "B34": "Floor mats, carpeted front",
  "B7G": "Sill plates, illuminated",
  "B9M": "Tail lamps, dark tint",
  "BCD": "Performance copper-free brake system",
  "BO3": "White Pearl Rally Stripes",
  "BO4": "Black Metallic Rally Stripes",
  "BRD": "Ceramic White Interior Package",
  "BRD": "Ceramic White Interior Accent Trim Package",
  "BRJ": "Adrenaline Red Interior Package",
  "BRJ": "Adrenaline Red Interior Accent Trim Package",
  "BTV": "Remote vehicle starter system",
  "C2U": "Silver Rally Stripes",
  "C3O": "Black Rally Stripes",
  "C68": "Air conditioning, single-zone automatic climate control",
  "C70": "Lighting, interior spectrum",
  "CF5": "Sunroof, power",
  "CFW": "Hood insert, visible Carbon Fiber weave",
  "CG3": "Emblem, Black Camaro fender badge",
  "CG3": "Emblem, Camaro fender badge",
  "CG6": "Emblem, Black Camaro fender badge with Red outline",
  "CJ2": "Air conditioning, dual-zone automatic climate control",
  "CM8": "Convertible top, power-folding",
  "D31": "Mirror, inside rearview manual day/night",
  "D52": "Spoiler, rear",
  "D5S": "Spoiler, rear, blade, Satin Black",
  "D5Z": "Spoiler, rear, stanchion",
  "D80": "Spoiler, decklid-mounted lip spoiler",
  "D88": "1LE Hash Mark Decal",
  "DD1": "Mirrors, outside heated power-adjustable and driver-side auto-dimming, body-color",
  "DD8": "Mirror, inside rearview auto-dimming",
  "DG7": "Mirrors, outside power-adjustable, body-color",
  "DRZ": "Rear Camera Mirror",
  "DSM": "Hood wrap, Satin Black",
  "DUU": "Black Center Stripe",
  "DUV": "Silver Center Stripe",
  "DVV": "Black Metallic Center Stripe",
  "DW7": "White Pearl Center Stripe",
  "DW8": "Black Metallic Center Stripe",
  "F55": "Magnetic Ride Control",
  "FE2": "Suspension, Sport",
  "FE3": "Suspension, Performance",
  "FE4": "Suspension, Performance",
  "FE9": "Emissions, Federal requirements",
  "FEA": "Suspension, Performance",
  "FTF": "Front splitter",
  "FTJ": "Front splitter",
  "G80": "Differential, limited slip",
  "G96": "Differential, electronic limited-slip",
  "G96": "Differential, electronic limited slip",
  "GT4": "Rear axle, 3.73 ratio",
  "GW6": "Rear axle, 3.27 ratio",
  "HRD": "Rear axle, 2.85 ratio",
  "HRE": "Rear axle, 2.77 ratio",
  "IOR": "Audio system, Chevrolet Infotainment 3 system, 7\" diagonal color touchscreen",
  "IOS": "Audio system, Chevrolet Infotainment 3 Plus system, 8\" diagonal HD color touchscreen",
  "IOT": "Audio system, Chevrolet Infotainment 3 Premium system with connected Navigation, 8\" diagonal HD color touchscreen",
  "J55": "Brakes, Brembo 4-piston front, performance, 4-wheel antilock, 4-wheel disc",
  "J6E": "Calipers, Yellow",
  "J6F": "Calipers, Red",
  "J6G": "Brakes, Brembo 4-piston front and rear, performance, 4-wheel antilock, 4-wheel disc",
  "J6H": "Brakes, Brembo 6-piston front and 4-piston rear, performance",
  "J6L": "Calipers, Orange",
  "J6M": "Brakes, Brembo Red, 6-piston front monobloc calipers, 4-piston rear calipers, 2-piece rotors, performance",
  "J6M": "Brakes, Brembo Red, 6-piston front monobloc calipers, 4-piston rear calipers, 2-piece rotors, performance",
  "JF5": "Pedals, sport alloy",
  "JL9": "Brakes, 4-wheel antilock, 4-wheel disc",
  "K05": "Engine block heater",
  "K4C": "Wireless Charging",
  "KA1": "Seats, heated driver and front passenger",
  "KB7": "Paddle-shift manual controls",
  "KC4": "Cooling, external engine oil cooler",
  "KD1": "Cooler, transmission oil",
  "KNR": "Cooler, rear differential",
  "KQV": "Seats, ventilated driver and front passenger",
  "KS9": "Shift knob, sueded microfiber-wrapped",
  "KTI": "Tire inflation kit",
  "LGX": "Engine, 3.6L V6, DI, VVT",
  "LT1": "Engine, 6.2L (376 ci) V8 DI",
  "LT4": "Engine, 6.2L supercharged V8",
  "LTG": "Engine, 2.0L Turbo, 4-cylinder, SIDI, VVT",
  "MN6": "Transmission, 6-speed manual",
  "MX0": "Transmission, 10-speed automatic",
  "MX0": "Transmission, 8-speed automatic",
  "N10": "Exhaust, dual-outlet stainless-steel",
  "N26": "Steering wheel, 3-spoke, sueded microfiber-wrapped, flat-bottom",
  "NB8": "Emissions override, California",
  "NB9": "Emissions override, state-specific",
  "NC7": "Emissions override, Federal",
  "NE1": "Emissions, Connecticut, Delaware, Maine, Maryland, Massachusetts, New Jersey, New York, Oregon, Pennsylvania, Rhode Island, Vermont and Washington state requirements",
  "NP5": "Steering wheel, leather-wrapped",
  "NPP": "Exhaust, dual-mode",
  "NPP": "Exhaust, dual-mode, performance",
  "NV9": "Steering, power",
  "P0G": "GM Commercial Link - 1 year of Service",
  "P0G": "GM Commercial Link – 1 year of Service",
  "P0H": "GM Commercial Link - 2 years of Service",
  "P0H": "GM Commercial Link – 2 years of Service",
  "P0I": "GM Commercial Link - 3 years of Service",
  "P0I": "GM Commercial Link – 3 years of Service",
  "P0J": "OnStar Additional 21 months of OnStar Fleet Safety and Security",
  "P0K": "OnStar Additional 33 months of OnStar Fleet Safety and Security",
  "P0L": "OnStar Additional 45 months of OnStar Fleet Safety and Security",
  "P0M": "OnStar Additional 21 months of OnStar Fleet Driver Remote Access",
  "P0M": "OnStar Additional 21 months of OnStar Fleet Remote Access",
  "P0N": "OnStar Additional 33 months of OnStar Fleet Driver Remote Access",
  "P0N": "OnStar Additional 33 months of OnStar Fleet Remote Access",
  "P0O": "OnStar Additional 45 months of OnStar Fleet Driver Remote Access",
  "P0O": "OnStar Additional 45 months of OnStar Fleet Remote Access",
  "P0P": "OnStar Additional 57 months of OnStar Fleet Driver Remote Access",
  "P0Q": "OnStar Additional 57 months of OnStar Fleet Safety and Security",
  "P0R": "OnStar Additional 9 months of OnStar Fleet Driver Remote Access",
  "P0U": "OnStar Additional 9 months of OnStar Fleet Safety and Security",
  "P0V": "OnStar Vehicle Insights - 1 year of Service",
  "P0V": "OnStar Vehicle Insights - 1 year of Service.",
  "P0W": "OnStar Vehicle Insights - 2 years of Service",
  "P0W": "OnStar Vehicle Insights - 2 years of Service.",
  "P0X": "OnStar Vehicle Insights - 3 years of Service",
  "P0X": "OnStar Vehicle Insights - 3 years of Service.",
  "P0Y": "OnStar Vehicle Insights - 4 years of Service",
  "P0Y": "OnStar Vehicle Insights - 4 years of Service.",
  "P0Z": "OnStar Vehicle Insights - 5 years of Service",
  "P0Z": "OnStar Vehicle Insights - 5 years of Service.",
  "P1R": "OnStar Additional 9 months of OnStar Fleet Assurance",
  "P1R": "OnStar Additional 9 months of OnStar Assurance for Tier3 Fleets",
  "P1R": "OnStar Additional 9 months of OnStar Fleet Essentials for Tier3 Fleets",
  "P1S": "OnStar Additional 21 months of OnStar Fleet Assurance",
  "P1S": "OnStar Additional 21 months of OnStar Assurance for Tier3 Fleets",
  "P1S": "OnStar Additional 21 months of OnStar Fleet Essentials for Tier3 Fleets",
  "P1T": "OnStar Additional 33 months of OnStar Fleet Assurance",
  "P1T": "OnStar Additional 33 months of OnStar Assurance for Tier3 Fleets",
  "P1T": "OnStar Additional 33 months of OnStar Fleet Essentials for Tier3 Fleets",
  "P1U": "OnStar Additional 45 months of OnStar Fleet Assurance",
  "P1U": "OnStar Additional 45 months of OnStar Assurance for Tier3 Fleets",
  "P1U": "OnStar Additional 45 months of OnStar Fleet Essentials for Tier3 Fleets",
  "P3H": "Bowties, Black, front and rear",
  "PCH": "LPO, Performance Enthusiast Package with Gray accents",
  "PCI": "LPO, Performance Enthusiast Package with Red accents",
  "PCJ": "LPO, Dark Tint Rear Lighting Package",
  "PCK": "LPO, Black Accent Exterior Package",
  "PCL": "LPO, Black Wheel Lug Nuts and Locks Package",
  "PCN": "LPO, Winter/Summer Floor Mats Package",
  "PCR": "LPO, Satin Black Front Splitter/Side Rockers Package",
  "PCU": "LPO, 4-Corner Brembo brake upgrade system in Red",
  "PCU": "LPO, 4-Corner Brembo Red Brake Upgrade Kit",
  "PCV": "LPO, RS/SS Interior Package",
  "PCW": "LPO, Camaro Logo Premium Carpeted Mats Package",
  "PCX": "LPO, Camaro Logo Package",
  "PCY": "LPO, Red Accent Exterior Package",
  "PDB": "LPO, Winter Protection Package",
  "PDL": "Design Package 1",
  "PDN": "Design Package 2",
  "PDP": "Design Package 3",
  "PDV": "LPO, Camaro Insignia Package",
  "PDX": "LPO, ZL1 Protection Package",
  "PDY": "LPO, Body-Color Spoiler with Wicker Package",
  "PKJ": "Wheels, 19\" x 11\" (48.3 cm x 27.9 cm) front and 19\" x 12\" (48.3 cm x 30.48 cm) rear low gloss Black-painted forged aluminum",
  "PPW": "Wireless Apple CarPlay/Wireless Android Auto",
  "PR6": "SiriusXM, Additional 9 months of the SXM Platinum Plan",
  "PR7": "SiriusXM, Additional 21 months of the SXM Platinum Plan",
  "PR8": "SiriusXM, Additional 33 months of the SXM Platinum Plan",
  "PRF": "3 Years of OnStar Remote Access",
  "PRF": "3 Years of Remote Access. The Remote Access Plan gives you simplified remote control of your properly equipped vehicle and unlocks a variety of great features in your myChevrolet mobile app. See dealer for details.",
  "Q7F": "Wheels, 20\" (50.8 cm) blade design aluminum",
  "Q7G": "Wheels, 20\" (50.8 cm) 5-split spoke Black forged aluminum",
  "R0F": "Tires, 245/40ZR20 front and 275/35ZR20 rear, blackwall, summer-only",
  "R0G": "Tires, 285/30R20 front and 305/30R20 rear, blackwall, summer-only",
  "R0H": "Tires, 245/50R18, blackwall, all-season",
  "R29": "Tires, 245/40R20, blackwall, all-season",
  "R6O": "Tires, 305/30R19 front and 325/30R19 rear, blackwall, summer-only",
  "R7Z": "OnStar Additional 57 months of OnStar Fleet Assurance",
  "R7Z": "OnStar Additional 57 months of OnStar Assurance for Tier3 Fleets",
  "R88": "LPO, Front illuminated and rear non-illuminated bowtie emblems in Black",
  "R88": "LPO, Illuminated Black bowtie emblem",
  "R8S": "OnStar In-Vehicle Coaching - 1 Year of Service",
  "R8V": "Not Equipped with Hood Insulator, see dealer for details.",
  "R9L": "Deleted 3 Years of OnStar Remote Access",
  "R9L": "Deleted 3 Years of Remote Access",
  "REG": "Wheels, 18\" (45.7 cm) Silver-painted aluminum",
  "RFR": "OnStar In-Vehicle Coaching - 1 year of Service",
  "RFS": "OnStar In-Vehicle Coaching - 2 Years of Service",
  "RFT": "OnStar In-Vehicle Coaching - 3 Years of Service",
  "RFU": "OnStar In-Vehicle Coaching - 4 Years of Service",
  "RFY": "OnStar In-Vehicle Coaching - 5 Years of Service",
  "RIK": "LPO, Black front and rear bowtie emblems",
  "RIN": "LPO, Camaro logo fender badge",
  "RMH": "LPO, Front splitter, Carbon Flash Metallic",
  "RMH": "LPO, Front splitter, Metallic Black",
  "RNX": "LPO, Outdoor vehicle cover",
  "RO1": "LPO, Black lower grille with Silver-painted inserts",
  "RO2": "LPO, Black lower grille with Gloss Black inserts",
  "RQ9": "Wheels, 20\" (50.8 cm) 5-split spoke premium Gray-painted, machined-face aluminum",
  "RQA": "Wheels, 20\" (50.8 cm) Silver-painted aluminum",
  "RSK": "Wheels, 20\" x 10\" (50.8 cm x 25.4 cm) front and 20\" x 11\" (50.8 cm x 27.9 cm) rear Satin Graphite forged aluminum",
  "RTH": "Wheels, 20\" (50.8 cm) 5-spoke Carbon Flash painted aluminum",
  "RTJ": "Wheels, 20\" (50.8 cm) 5-spilt spoke bright Silver-painted aluminum",
  "RTQ": "Wheels, 20\" x 10\" (50.8 cm x 25.4 cm) front and 20\" x 11\" (50.8 cm x 27.9 cm) rear Dark Graphite premium paint, forged aluminum",
  "RVK": "LPO, Performance air intake",
  "RWH": "LPO, Indoor vehicle cover",
  "RWJ": "LPO, Outdoor vehicle cover",
  "RX0": "LPO, 4 Piston Brembo rear calipers in Red",
  "RX0": "LPO, 4 Piston Rear Brake Kit",
  "RXH": "LPO, Silver RS wheel center caps",
  "RXJ": "LPO, Silver SS wheel center caps",
  "RY2": "LPO, Black Metallic Hash Mark Stripes",
  "RY2": "LPO, Black Metallic Hash Mark Decals",
  "RZ3": "LPO, Front splitter",
  "RZ3": "LPO, Front fascia extension",
  "RZB": "LPO, Black lower grille with Red Hot inserts",
  "S0O": "LPO, Illuminated footwells",
  "S0U": "LPO, Black sueded knee pads",
  "S0V": "LPO, White knee pads",
  "S54": "LPO, Navigation upgrade kit",
  "SA7": "LPO, Suede shift knob and boot kit",
  "SB2": "LPO, Carbon Flash Metallic wing spoiler",
  "SB3": "LPO, ZL1 SPEC rear spoiler, body-color",
  "SB3": "LPO, ZL1 rear spoiler, body-color",
  "SB7": "LPO, Red Spider Stripes",
  "SB9": "LPO, Satin Black Spider Stripes",
  "SB9": "LPO, Black Spider Stripes",
  "SB9": "LPO, Black Metallic Spider Stripes",
  "SC1": "LPO, Sway bar suspension upgrade system",
  "SC1": "LPO, Performance Handling Package",
  "SCG": "LPO, 6.2L Strut tower brace in Black",
  "SCJ": "LPO, Suspension Handling Package, 1LE Track Pack - V8",
  "SCY": "LPO, Dark finish tail lamps",
  "SF8": "LPO, Silver Body-Side Spear Stripes",
  "SF8": "LPO, Silver Body-Side Spear Decals",
  "SF9": "LPO, Blue Hash Mark Stripes",
  "SF9": "LPO, Blue Hash Mark Decals",
  "SFA": "LPO, Red Stinger Stripe",
  "SFC": "LPO, White Pearl Hash Mark Stripes",
  "SFC": "LPO, White Pearl Hash Mark Decals",
  "SFE": "LPO, Wheel locks",
  "SFZ": "LPO, Camaro fender badge, Black",
  "SG3": "LPO, Lowering suspension upgrade system",
  "SG3": "LPO, Suspension lowering kit",
  "SGE": "Wheels, 18\" (45.7 cm) 5-split spoke Silver-painted aluminum",
  "SGE": "Wheels, 18\" (45.7 cm) Silver-painted aluminum",
  "SH1": "LPO, Embroidered center console lid with Camaro badge",
  "SH2": "LPO, Embroidered center console lid",
  "SHL": "LPO, 20\" (50.8 cm) 5-spoke gloss Black wheels with Red outline stripe",
  "SHQ": "LPO, Silver Hash Mark Stripes",
  "SHQ": "LPO, Silver Hash Mark Decals",
  "SHS": "LPO, Satin Black Hood Stripe with Silver Ice Metallic Hash Mark",
  "SHT": "Spoiler stripe",
  "SHU": "LPO, Satin Black Hood Stripe with Red Hot Hash Mark",
  "SIA": "LPO, Wicker bill",
  "SIB": "LPO, Interior spectrum lighting, Dark Night",
  "SIC": "LPO, Interior spectrum lighting, Red Day, Satin Red and Gloss Red pattern finish",
  "SJ8": "LPO, Interior spectrum lighting, Structura",
  "SKW": "LPO, 20\" (50.8 cm) 5-split spoke machined-face wheels",
  "SL1": "LPO, Indoor vehicle cover",
  "SL2": "LPO, Front splitter",
  "SL2": "LPO, Front fascia extension, Satin Black, second generation",
  "SLN": "LPO, Strut tower brace",
  "SNB": "LPO, Silver Spider Stripes",
  "SNC": "LPO, White Pearl Spider Stripes",
  "SNE": "LPO, Silver Stinger Stripe",
  "SNG": "LPO, Red Hash Mark Stripes",
  "SNG": "LPO, Red Hash Mark Decals",
  "SNH": "LPO, White Pearl Body-Side Spear Stripes",
  "SNH": "LPO, White Pearl Body-Side Spear Decals",
  "SNJ": "LPO, Satin Black Stinger Stripe",
  "SNJ": "LPO, Black Metallic Stinger Stripe",
  "SNM": "LPO, White Pearl Stinger Stripe",
  "SNP": "LPO, Red Body-Side Spear Stripes",
  "SNP": "LPO, Red Body-Side Spear Decals",
  "SNQ": "LPO, Gray Body-Side Spear Stripes",
  "SNQ": "LPO, Gray Body-Side Spear Decals",
  "SNS": "LPO, Blue Body-Side Spear Stripes",
  "SNS": "LPO, Blue Body-Side Spear Decals",
  "SPY": "LPO, Black lug nuts",
  "SPZ": "LPO, Black wheel locks",
  "SRI": "Wheels, 20\" (50.8 cm) Black-painted aluminum with Red accents",
  "STI": "LPO, Satin Black rocker moldings",
  "T42": "Spoiler, rear, visible weave carbon fiber",
  "TDM": "Teen Driver",
  "U2K": "SiriusXM",
  "U2K": "SiriusXM Radio",
  "U77": "Antenna, integral rear window",
  "UB3": "Antenna, AM/FM",
  "UD7": "Rear Park Assist",
  "UDD": "Driver Information Center, color display",
  "UE1": "OnStar and Chevrolet connected services capable",
  "UEU": "Forward Collision Alert",
  "UFG": "Rear Cross Traffic Alert",
  "UHS": "Driver Information Center",
  "UKC": "Lane Change Alert",
  "UKC": "Side Blind Zone Alert",
  "UMN": "Speedometer, miles/kilometers",
  "UPG": "Bluetooth for phone",
  "UQ3": "Audio system feature, 6-speaker system",
  "UQA": "Audio system feature, Bose premium 9-speaker system",
  "UQA": "Audio system feature, Bose premium 7-speaker system",
  "UQT": "Performance data and video recorder",
  "UV6": "Head-Up Display",
  "UVB": "HD Rear Vision Camera",
  "UVD": "Steering wheel, heated",
  "V03": "Cooling system, extra capacity",
  "V18": "Cooler, engine coolant",
  "VAV": "LPO, All-weather floor mats",
  "VDN": "LPO, Indoor vehicle cover",
  "VEB": "LPO, Sport pedals kit",
  "VGS": "LPO, Outdoor vehicle cover, Gray, ZL1 logo",
  "VK3": "License plate bracket, front",
  "VLI": "LPO, All-weather cargo mat",
  "VLN": "LPO, Windscreen",
  "VPO": "LPO, Gray Hash Mark Stripes",
  "VPO": "LPO, Gray Hash Mark Decals",
  "VPW": "LPO, Black Metallic Body-Side Spear Stripes",
  "VPW": "LPO, Black Metallic Body-Side Spear Decals",
  "VQG": "LPO, Weather Protection Package",
  "VQL": "LPO, Fuel filler door in Black with visible carbon fiber insert",
  "VQL": "LPO, Fuel door with visible carbon fiber insert",
  "VRU": "LPO, Outdoor vehicle cover, Gray",
  "VRV": "LPO, Body-color painted splash guards",
  "VTA": "LPO, Black exhaust tip",
  "VTD": "LPO, Ground effects, Carbon Flash Metallic",
  "VTD": "LPO, Ground effects, Metallic Black",
  "VTF": "LPO, Embroidered center console lid",
  "VTG": "LPO, White Interior Trim Kit",
  "VTU": "LPO, Fuel filler door in Black with Gloss Black insert",
  "VTU": "LPO, Gloss Black fuel door",
  "VUP": "Redline Edition graphics",
  "VUP": "LPO, Redline Edition graphics",
  "VV4": "Wi-Fi Hotspot capable",
  "VV4": "4G LTE Wi-Fi Hotspot capable",
  "VV4": "Chevrolet 4G LTE",
  "VW9": "LPO, Black SS wheel center caps",
  "VWD": "LPO, Gloss Black wheel center caps with Silver bowtie",
  "VY7": "Shift knob, leather-wrapped",
  "VYV": "LPO, Short-throw shifter",
  "VYW": "LPO, Floor mats, premium carpeted",
  "VYX": "LPO, Painted engine cover",
  "W0D": "LPO, Fuel filler door in Black with Red Hot insert",
  "W0D": "LPO, Red Hot fuel door",
  "W0E": "LPO, Fuel filler door in Black with Silver Ice Metallic insert",
  "W0E": "LPO, Silver Ice Metallic fuel door",
  "W1V": "LPO, Floor mats, premium carpeted",
  "W2D": "LPO, Cargo net",
  "WBL": "Redline Edition",
  "WGK": "LPO, Red Interior Trim Kit",
  "WGL": "LPO, Kalahari knee pads",
  "WGT": "LPO, Black Interior Trim Kit",
  "WHA": "LPO, Red knee pads",
  "WL2": "LPO, Floor mats, premium carpeted with 1LE performance logo",
  "WL3": "LPO, Premium carpeted floor mats",
  "WR1": "Wheels, 20\" (50.8 cm) 5-split spoke polished forged aluminum with Black star center cap",
  "WR1": "Wheels, 20\" (50.8 cm) 5-split spoke polished forged with Black star center cap",
  "WRS": "RS Package",
  "X56": "Garage 56 Edition",
  "XLC": "Launch control, custom",
  "Y3W": "Technology Package",
  "Y4Q": "Heavy-Duty Cooling and Brake Package",
  "YF5": "Emissions, California state requirements",
  "Z4B": "Camaro Collector Edition - LT/LT1/SS/ZL1 models",
  "ZN2": "Convenience and Lighting Package",
}

const corvetteRpo = {
  "379": "SEAT BELT COLOR, ORANGE",
  "719": "SEAT BELT COLOR, BLACK",
  "36S": "COMPETITION YELLOW CUSTOM LEATHER STITCH",
  "37S": "SANTORINI BLUE CUSTOM LEATHER STITCH",
  "38S": "ADRENALINE RED CUSTOM LEATHER STITCH",
  "3A9": "SEAT BELT COLOR, SANTORINI BLUE",
  "3F9": "SEAT BELT COLOR, TORCH RED",
  "3M9": "SEAT BELT COLOR, YELLOW",
  "3N9": "SEAT BELT COLOR, NATURAL",
  "5DG": "LPO, 19″ X 8.5″ (48.3 CM X 21.6 CM) FRONT AND 20″ X 11″ (50.8 CM X 25.4 CM) REAR 20-SPOKE TECH BRONZE ALUMINUM WHEELS",
  "5DH": "LPO, 20″ X 10″ (50.8 CM X 25.4 CM) FRONT AND 21″ X 13″ (53.3 CM X 33 CM) REAR SPIDER DESIGN, SATIN GRAPHITE FORGED ALUMINUM WITH RED STRIPE WHEELS",
  "5DK": "LPO, 20″ X 10″ (50.8 CM X 25.4 CM) FRONT AND 21″ X 13″ (53.3 CM X 33 CM) REAR SPIDER DESIGN, TECH BRONZE FORGED ALUMINUM WHEELS",
  "5DO": "LPO, 19″ X 8.5″ (48.3 CM X 21.6 CM) FRONT AND 20″ X 11″ (50.8 CM X 25.4 CM) REAR 15-SPOKE BRIGHT POLISHED ALUMINUM WHEELS",
  "5JR": "LPO, OUTSIDE MIRROR COVERS IN VISIBLE CARBON FIBER",
  "5V5": "LPO, SPOILER, VISIBLE CARBON FIBER",
  "5V7": "LPO, BLACK GROUND EFFECTS",
  "5VM": "LPO, VISIBLE CARBON FIBER GROUND EFFECTS",
  "5W8": "LPO, CARBON FIBER GROUND EFFECTS, CARBON FLASH METALLIC-PAINTED",
  "5ZC": "LPO, JAKE LOGO WHEEL CENTER CAPS",
  "5ZD": "LPO, CARBON FLASH WHEEL CENTER CAPS WITH CROSSED FLAGS LOGO",
  "5ZU": "LPO, HIGH WING SPOILER",
  "5ZV": "LPO, THREE-STANCHION HIGH WING SPOILER, CARBON FLASH METALLIC-PAINTED",
  "5ZW": "LPO, TWO-STANCHION SPOILER, VISIBLE CARBON FIBER",
  "5ZZ": "LPO, HIGH WING SPOILER, CARBON FLASH METALLIC-PAINTED",
  "A2X": "SEAT ADJUSTER, DRIVER 8-WAY POWER",
  "AE4": "SEATS, COMPETITION SPORT BUCKET",
  "AH2": "SEATS, GT2 BUCKET",
  "AHE": "SEAT ADJUSTER, DRIVER POWER BOLSTER",
  "AHH": "SEAT ADJUSTER, PASSENGER POWER BOLSTER",
  "AL9": "SEAT ADJUSTER, POWER DRIVER LUMBAR CONTROL",
  "AP9": "CARGO NETS",
  "AQ9": "SEATS, GT1 BUCKET",
  "AQA": "MEMORY DRIVER AND PASSENGER CONVENIENCE PACKAGE",
  "AT9": "SEAT ADJUSTER, POWER PASSENGER LUMBAR CONTROL",
  "B4Z": "PERFORMANCE TRACTION MANAGEMENT",
  "B6P": "COUPE ENGINE APPEARANCE PACKAGE",
  "BAZ": "STEALTH INTERIOR TRIM PACKAGE",
  "BC7": "LT2 ENGINE COVER",
  "BCP": "LT2 ENGINE COVER",
  "BCS": "LT2 ENGINE COVER",
  "BV4": "PLAQUE, PERSONALIZED",
  "C2M": "CARBON FIBER DUAL ROOF PACKAGE",
  "C2Q": "BODY-COLOR DUAL ROOF PACKAGE",
  "C2Z": "ROOF PANEL, VISIBLE CARBON FIBER WITH BODY-COLOR SURROUND",
  "CAV": "LPO, CONTOURED CARGO AREA LINERS WITH JAKE LOGO",
  "CC3": "ROOF PANEL, TRANSPARENT, REMOVABLE",
  "CF7": "ROOF PANEL, BODY-COLOR, REMOVABLE",
  "CF8": "ROOF PANEL, ELECTROCHROMIC DIMMING",
  "CFC": "CONVERTIBLE TOP, RETRACTABLE, POWER-FOLDING HARD TOP",
  "CFV": "GROUND EFFECTS, VISIBLE CARBON FIBER",
  "CFX": "PLAQUE, PERSONALIZED WITH CORVETTE MUSEUM LOGO",
  "CFY": "PLAQUE, 70TH ANNIVERSARY",
  "CFZ": "GROUND EFFECTS, CARBON FIBER, CARBON FLASH-PAINTED",
  "CJ2": "AIR CONDITIONING, DUAL-ZONE AUTOMATIC CLIMATE CONTROL",
  "CM9": "CONVERTIBLE TOP, RETRACTABLE",
  "D30": "COLOR COMBINATION OVERRIDE",
  "D3V": "ENGINE LIGHTING",
  "D84": "CONVERTIBLE TOP, CARBON FLASH-PAINTED NACELLES AND ROOF",
  "D86": "CONVERTIBLE TOP, CARBON FLASH-PAINTED NACELLES AND BODY-COLOR ROOF",
  "DPB": "CARBON FLASH WITH BLUE ACCENT FULL LENGTH DUAL RACING STRIPES",
  "DPC": "CARBON FLASH WITH YELLOW ACCENT FULL LENGTH DUAL RACING STRIPES",
  "DPG": "CARBON FLASH WITH ORANGE ACCENT FULL LENGTH DUAL RACING STRIPES",
  "DPL": "CARBON FLASH WITH RED ACCENT FULL LENGTH DUAL RACING STRIPES",
  "DPT": "CARBON FLASH WITH SILVER ACCENT FULL LENGTH DUAL RACING STRIPES",
  "DRG": "MIRRORS, OUTSIDE, CARBON FLASH METALLIC-PAINTED",
  "DRZ": "REAR CAMERA MIRROR",
  "DSY": "EDGE ORANGE FULL LENGTH DUAL RACING STRIPES",
  "DSZ": "EDGE RED FULL LENGTH DUAL RACING STRIPES",
  "DT0": "COMPETITION YELLOW FULL LENGTH DUAL RACING STRIPES",
  "DTB": "ELECTRIC BLUE FULL LENGTH DUAL RACING STRIPES",
  "DTF": "70TH ANNIVERSARY SATIN MATRIX GRAY FULL LENGTH DUAL RACING STRIPES",
  "DTH": "CARBON FLASH METALLIC FULL LENGTH DUAL RACING STRIPES",
  "DTK": "70TH ANNIVERSARY SATIN BLACK METALLIC FULL LENGTH DUAL RACING STRIPES",
  "DUB": "STERLING SILVER FULL LENGTH DUAL RACING STRIPES",
  "DUK": "ASYMMETRICAL ADRENALINE RED/CARBON FLASH FULL LENGTH DUAL RACING STRIPES",
  "DUW": "EDGE BLUE FULL LENGTH DUAL RACING STRIPES",
  "DWK": "MIRRORS, OUTSIDE HEATED, POWER-ADJUSTABLE",
  "DX0": "MIDNIGHT GRAY FULL LENGTH DUAL RACING STRIPES",
  "DY0": "DISPLAY HOOD, CARBON FIBER",
  "DYX": "MIRRORS, OUTSIDE HEATED, POWER-ADJUSTABLE",
  "DZU": "CARBON FLASH/COMPETITION YELLOW STINGER STRIPE",
  "DZV": "CARBON FLASH/MIDNIGHT SILVER STINGER STRIPE",
  "DZX": "CARBON FLASH/EDGE RED STINGER STRIPE",
  "E60": "FRONT LIFT ADJUSTABLE HEIGHT",
  "EFA": "EXTERIOR ACCENTS, SHADOW GRAY",
  "EFR": "EXTERIOR ACCENTS, CARBON FLASH",
  "EFY": "EXTERIOR ACCENTS, BODY-COLOR",
  "ERI": "BATTERY PROTECTION PACKAGE",
  "ETV": "EXTERIOR TRIM, CARBON FIBER SPLIT WINDOW TRIM, PAINTED BODY-COLOR",
  "EYK": "CHROME EXTERIOR BADGE PACKAGE",
  "EYT": "CARBON FLASH EXTERIOR BADGE PACKAGE",
  "FA5": "TRIM, INTERIOR",
  "FA6": "TRIM, INTERIOR",
  "FE1": "SUSPENSION, CORVETTE STANDARD",
  "FE2": "SUSPENSION, MAGNETIC SELECTIVE RIDE CONTROL",
  "FE3": "SUSPENSION, Z51 PERFORMANCE",
  "FE4": "SUSPENSION, Z51 PERFORMANCE WITH MAGNETIC SELECTIVE RIDE CONTROL",
  "FE5": "SUSPENSION, PERFORMANCE",
  "FE6": "SUSPENSION, PERFORMANCE",
  "FE7": "SUSPENSION, Z07",
  "FE8": "SUSPENSION, PERFORMANCE WITH MAGNETIC SELECTIVE RIDE CONTROL",
  "FE9": "EMISSIONS, FEDERAL REQUIREMENTS",
  "FED": "SUSPENSION, ZER",
  "FEJ": "SUSPENSION, ZTK WITH MAGNETIC SELECTIVE RIDE CONTROL",
  "G0J": "DIFFERENTIAL, MECHANICAL LIMITED-SLIP",
  "G0K": "REAR AXLE, 5.56 RATIO",
  "G96": "DIFFERENTIAL, ELECTRONIC LIMITED-SLIP",
  "GM7": "REAR AXLE, PERFORMANCE RATIO",
  "HP1": "FRONT AXLE, ELECTRIFIED PROPULSION",
  "IOK": "AUDIO SYSTEM, CHEVROLET INFOTAINMENT 3 PREMIUM SYSTEM WITH GOOGLE BUILT-IN COMPATIBILITY",
  "IOS": "AUDIO SYSTEM, CHEVROLET INFOTAINMENT 3 PLUS SYSTEM, 8″ DIAGONAL HD COLOR TOUCHSCREEN",
  "IOT": "AUDIO SYSTEM, CHEVROLET INFOTAINMENT 3 PREMIUM SYSTEM WITH CONNECTED NAVIGATION, 8″ DIAGONAL HD COLOR TOUCHSCREEN",
  "IVE": "INFOTAINMENT SYSTEM WITH GOOGLE BUILT-IN",
  "IWE": "SUEDED MICROFIBER-WRAPPED UPPER INTERIOR TRIM PACKAGE",
  "J55": "BRAKES, Z51 PERFORMANCE",
  "J56": "BRAKES, 4-WHEEL ANTILOCK, 4-WHEEL DISC",
  "J57": "BRAKES, 4-WHEEL ANTILOCK, 4-WHEEL DISC",
  "J58": "BRAKES, 4-WHEEL ANTILOCK, 4-WHEEL DISC",
  "J59": "BRAKES, 4-WHEEL ANTILOCK, 4-WHEEL DISC, CARBON CERAMIC, 10-PISTON FRONT, 6-PISTON REAR",
  "J6A": "CALIPERS, BLACK",
  "J6B": "CALIPERS, BLUE",
  "J6D": "CALIPERS, DARK GRAY METALLIC",
  "J6E": "CALIPERS, VELOCITY YELLOW",
  "J6F": "CALIPERS, BRIGHT RED",
  "J6L": "CALIPERS, ORANGE",
  "J6N": "CALIPERS, EDGE RED",
  "J6O": "CALIPERS, BRONZE-PAINTED",
  "JL9": "BRAKES, 4-WHEEL ANTILOCK, 4-WHEEL DISC",
  "K4C": "WIRELESS CHARGING",
  "K7A": "WIRELESS PHONE CHARGING",
  "K7B": "WIRELESS PHONE CHARGING",
  "KI3": "STEERING WHEEL, HEATED",
  "KQV": "SEATS, HEATED AND VENTED DRIVER AND PASSENGER",
  "LT2": "ENGINE, 6.2L V8 DI",
  "LT6": "ENGINE, 5.5L V8 DI",
  "LT7": "ENGINE, 5.5L V8 TWIN TURBO",
  "M1K": "TRANSMISSION, 8-SPEED DUAL CLUTCH",
  "M1L": "TRANSMISSION, 8-SPEED DUAL CLUTCH",
  "M1M": "TRANSMISSION, 8-SPEED DUAL CLUTCH, INCLUDES MANUAL AND AUTO MODES",
  "MLH": "TRANSMISSION, 8-SPEED DUAL CLUTCH, INCLUDES MANUAL AND AUTO MODES",
  "N26": "STEERING WHEEL, SUEDED MICROFIBER-WRAPPED",
  "N2Z": "STEERING WHEEL, CARBON FIBER AND SUEDED MICROFIBER-WRAPPED",
  "N38": "STEERING COLUMN, POWER TILT AND TELESCOPIC",
  "N3W": "STEERING WHEEL, CARBON FIBER AND LEATHER-WRAPPED",
  "NB8": "EMISSIONS OVERRIDE, CALIFORNIA",
  "NB9": "EMISSIONS OVERRIDE, STATE-SPECIFIC",
  "NC7": "EMISSIONS OVERRIDE, FEDERAL",
  "NE1": "EMISSIONS",
  "NGA": "EXHAUST TIPS, BLACK",
  "NK4": "STEERING WHEEL, LEATHER-WRAPPED",
  "NPP": "EXHAUST, PERFORMANCE",
  "P0H": "12 MONTHS ONSTAR CONNECT PLUS",
  "P0I": "24 MONTHS ONSTAR CONNECT PLUS",
  "P0J": "24 MONTHS ONSTAR PROTECT",
  "P0K": "36 MONTHS ONSTAR PROTECT",
  "P0L": "48 MONTHS ONSTAR PROTECT",
  "P0M": "ONSTAR ADDITIONAL 21 MONTHS OF ONSTAR FLEET DRIVER REMOTE ACCESS",
  "P0N": "ONSTAR ADDITIONAL 33 MONTHS OF ONSTAR FLEET DRIVER REMOTE ACCESS",
  "P0O": "ONSTAR ADDITIONAL 45 MONTHS OF ONSTAR FLEET DRIVER REMOTE ACCESS",
  "P0P": "ONSTAR ADDITIONAL 57 MONTHS OF ONSTAR FLEET DRIVER REMOTE ACCESS",
  "P0Q": "60 MONTHS ONSTAR PROTECT",
  "P0R": "ONSTAR ADDITIONAL 9 MONTHS OF ONSTAR FLEET DRIVER REMOTE ACCESS",
  "P0U": "12 MONTHS ONSTAR PROTECT",
  "P0V": "12 MONTHS ONSTAR TELEMATICS",
  "P0W": "24 MONTHS ONSTAR TELEMATICS",
  "P0X": "36 MONTHS ONSTAR TELEMATICS",
  "P0Y": "48 MONTHS ONSTAR TELEMATICS",
  "P0Z": "60 MONTHS ONSTAR TELEMATICS",
  "P1R": "ONSTAR ADDITIONAL 9 MONTHS OF ONSTAR FLEET ASSURANCE",
  "P1S": "ONSTAR ADDITIONAL 21 MONTHS OF ONSTAR FLEET ASSURANCE",
  "P1T": "ONSTAR ADDITIONAL 33 MONTHS OF ONSTAR FLEET ASSURANCE",
  "P1U": "ONSTAR ADDITIONAL 45 MONTHS OF ONSTAR FLEET ASSURANCE",
  "PBC": "CUSTOMER ENGINE BUILD PROGRAM",
  "PCU": "LPO, STINGRAY PROTECTION PACKAGE",
  "PCX": "LPO, TECH BRONZE ACCENT PACKAGE",
  "PCZ": "LPO, TECH BRONZE ACCENT PACKAGE",
  "PDA": "LPO, JAKE C8.R GRAPHICS PACKAGE",
  "PDV": "LPO, STINGRAY R APPEARANCE PACKAGE",
  "PDY": "LPO, ROADSIDE SAFETY PACKAGE",
  "PEF": "LPO, CONTOURED LINER PROTECTION PACKAGE",
  "PIN": "CUSTOMER VIN ENDING RESERVATION",
  "PPW": "WIRELESS APPLE CARPLAY/WIRELESS ANDROID AUTO",
  "PQG": "36 MONTHS ONSTAR CONNECT PLUS",
  "PQH": "48 MONTHS ONSTAR CONNECT PLUS",
  "PQI": "60 MONTHS ONSTAR CONNECT PLUS",
  "PR6": "SIRIUSXM, ADDITIONAL 9 MONTHS OF THE SXM PLATINUM PLAN",
  "PR7": "SIRIUSXM, ADDITIONAL 21 MONTHS OF THE SXM PLATINUM PLAN",
  "PR8": "SIRIUSXM, ADDITIONAL 33 MONTHS OF THE SXM PLATINUM PLAN",
  "PRF": "3 YEARS OF REMOTE ACCESS. THE REMOTE ACCESS PLAN GIVES YOU SIMPLIFIED REMOTE CONTROL OF YOUR PROPERLY EQUIPPED VEHICLE AND UNLOCKS A VARIETY OF GREAT FEATURES IN YOUR MYCHEVROLET MOBILE APP. SEE DEALER FOR DETAILS.",
  "Q8P": "WHEELS, 19″ X 8.5″ (48.3 CM X 21.6 CM) FRONT AND 20″ X 11″ (50.8 CM X 27.9 CM) REAR 5-OPEN-SPOKE BRIGHT SILVER-PAINTED ALUMINUM",
  "Q8Q": "WHEELS, 19″ X 8.5″ (48.3 CM X 21.6 CM) FRONT AND 20″ X 11″ (50.8 CM X 27.9 CM) REAR 5-OPEN-SPOKE CARBON FLASH-PAINTED ALUMINUM WITH MACHINED EDGE",
  "Q8S": "WHEELS, 19″ X 8.5″ (48.3 CM X 21.6 CM) FRONT AND 20″ X 11″ (50.8 CM X 27.9 CM) REAR 5-TRIDENT-SPOKE MACHINED-FACE STERLING SILVER-PAINTED ALUMINUM",
  "Q8T": "WHEELS, 19″ X 8.5″ (48.3 CM X 21.6 CM) FRONT AND 20″ X 11″ (50.8 CM X 27.9 CM) REAR 5-TRIDENT-SPOKE MACHINED-FACE SPECTRA GRAY-PAINTED ALUMINUM",
  "Q99": "WHEELS, 19″ X 8.5″ (48.3 CM X 21.6 CM) FRONT AND 20″ X 11″ (50.8 CM X 27.9 CM) REAR 20-SPOKE BRIGHT MACHINED-FACE FORGED ALUMINUM",
  "Q9A": "WHEELS, 19″ X 8.5″ (48.3 CM X 21.6 CM) FRONT AND 20″ X 11″ (50.8 CM X 27.9 CM) REAR 20-SPOKE MIDNIGHT GRAY FORGED ALUMINUM WITH RED STRIPE",
  "Q9I": "WHEELS, 19″ X 8.5″ (48.3 CM X 21.6 CM) FRONT AND 20″ X 11″ (50.8 CM X 27.9 CM) REAR 20-SPOKE GLOSS BLACK FORGED ALUMINUM",
  "Q9O": "WHEELS, 19″ X 8.5″ (48.3 CM X 21.6 CM) FRONT AND 20″ X 11″ (50.8 CM X 27.9 CM) REAR 5-SPLIT-SPOKE SATIN GRAPHITE WITH MACHINED EDGE FORGED ALUMINUM",
  "Q9Y": "WHEELS, 19″ X 8.5″ (48.3 CM X 21.6 CM) FRONT AND 20″ X 11″ (50.8 CM X 27.9 CM) REAR 5-SPLIT-SPOKE MACHINED-FACE STERLING SILVER-PAINTED FORGED ALUMINUM",
  "QE5": "WHEELS, 19″ X 8.5″ (48.3 CM X 21.6 CM) FRONT AND 20″ X 11″ (50.8 CM X 27.9 CM) REAR 5-SPLIT-SPOKE GLOSS BLACK FORGED ALUMINUM",
  "QEB": "WHEELS, 19″ X 8.5″ (48.3 CM X 21.6 CM) FRONT AND 20″ X 11″ (50.8 CM X 27.9 CM) REAR 5-SPLIT-SPOKE PEARL NICKEL FORGED ALUMINUM",
  "QUD": "TIRES, 245/35ZR19 FRONT AND 305/30ZR20 REAR, BLACKWALL, HIGH PERFORMANCE",
  "R6P": "3 YEARS SIRIUSXM",
  "R6X": "CUSTOM INTERIOR TRIM AND SEAT COMBINATION",
  "R7Z": "ONSTAR ADDITIONAL 57 MONTHS OF ONSTAR FLEET ASSURANCE",
  "R88": "LPO, ILLUMINATED CROSSED FLAGS EMBLEM",
  "R8C": "CORVETTE MUSEUM DELIVERY",
  "R8E": "GAS GUZZLER TAX",
  "R8G": "12 MONTHS ONSTAR ONE FLEET",
  "R8P": "36 MONTHS ONSTAR ONE FLEET",
  "R8S": "ONSTAR IN-VEHICLE COACHING – 1 YEAR OF SERVICE",
  "R8W": "60 MONTHS ONSTAR ONE FLEET",
  "R8Z": "48 MONTHS ONSTAR ONE FLEET",
  "R9L": "REMOVES ONSTAR BASICS (ONSTAR FLEET BASICS FOR FLEET)",
  "R9V": "MOBILE SERVICE PLUS",
  "R9W": "DELETED MOBILE SERVICE PLUS",
  "R9Y": "MOBILE SERVICE PLUS",
  "RCC": "LPO, LT2 ENGINE COVER IN EDGE RED",
  "RCD": "LPO, LT2 ENGINE COVER IN STERLING SILVER",
  "RFH": "24 MONTHS ONSTAR ONE FLEET",
  "RFR": "ONSTAR IN-VEHICLE COACHING – 1 YEAR OF SERVICE",
  "RFS": "ONSTAR IN-VEHICLE COACHING – 2 YEARS OF SERVICE",
  "RFT": "ONSTAR IN-VEHICLE COACHING – 3 YEARS OF SERVICE",
  "RFU": "ONSTAR IN-VEHICLE COACHING – 4 YEARS OF SERVICE",
  "RFY": "ONSTAR IN-VEHICLE COACHING – 5 YEARS OF SERVICE",
  "RIA": "LPO, ALL-WEATHER FLOOR LINERS",
  "RIK": "LPO, REAR CORVETTE SCRIPT BADGE IN TORCH RED",
  "RIN": "LPO, REAR CORVETTE SCRIPT BADGE IN ARCTIC WHITE",
  "RNX": "LPO, PREMIUM OUTDOOR CAR COVER, GRAY WITH STINGRAY LOGO AND ACCESS PANELS",
  "ROU": "WHEELS, 20″ X 10″ (50.8 CM X 25.4 CM) FRONT AND 21″ X 13″ (53.3 CM X 33 CM) REAR PEARL NICKEL FORGED ALUMINUM",
  "ROX": "WHEELS, 20″ X 10″ (50.8 CM X 25.4 CM) FRONT AND 21″ X 13″ (53.3 CM X 33 CM) REAR CARBON FLASH WITH MACHINED EDGE FORGED ALUMINUM",
  "ROY": "WHEELS, 20″ X 10″ (50.8 CM X 25.4 CM) FRONT AND 21″ X 13″ (53.3 CM X 33 CM) REAR CARBON FLASH-PAINTED CARBON FIBER",
  "ROZ": "WHEELS, 20″ X 10″ (50.8 CM X 25.4 CM) FRONT AND 21″ X 13″ (53.3 CM X 33 CM) REAR VISIBLE CARBON FIBER",
  "RWH": "LPO, PREMIUM INDOOR CAR COVER, BLACK WITH CROSSED FLAGS LOGO",
  "RWJ": "LPO, PREMIUM OUTDOOR CAR COVER, GRAY WITH CROSSED FLAGS LOGO AND CORVETTE SILHOUETTE",
  "RWU": "LPO, CARGO AREA ORGANIZER, COLLAPSIBLE",
  "RXH": "LPO, SILVER WHEEL CENTER CAPS WITH STINGRAY LOGO AND RED OUTLINE",
  "RXI": "LPO, LT6 ENGINE COVER IN VISIBLE CARBON FIBER",
  "RXJ": "LPO, BLACK WHEEL CENTER CAPS WITH GRAY STINGRAY LOGO",
  "RYQ": "LPO, VISIBLE CARBON FIBER DOOR INTAKE TRIM",
  "RYT": "LPO, FIRST AID KIT",
  "RZ9": "LPO, VISIBLE CARBON FIBER GRILLE INSERT",
  "S08": "LPO, HIGHWAY SAFETY KIT",
  "S2L": "LPO, SET OF PREMIUM LEATHER WEEKEND/TRAVEL BAGS",
  "S47": "LPO, CHROME LUG NUTS",
  "SB7": "LPO, CORVETTE RACING THEMED GRAPHICS PACKAGE WITH JAKE AND STINGRAY R LOGOS",
  "SBT": "LPO, DUAL ROOF",
  "SC7": "LPO, ROOF PANEL STORAGE POUCH",
  "SDA": "LPO, BLACK TOW HOOK",
  "SFE": "LPO, CHROME WHEEL LOCKS",
  "SFZ": "LPO, DARK STEALTH CROSSED FLAGS EMBLEM",
  "SG1": "LPO, Z06 BADGES IN EDGE RED",
  "SHQ": "LPO, FENDER HASH STRIPES, SILVER WITH CARBON FLASH METALLIC ACCENT",
  "SHT": "LPO, JAKE HOOD GRAPHIC WITH TECH BRONZE ACCENT",
  "SHW": "LPO, FENDER HASH STRIPES, CARBON FLASH METALLIC WITH EDGE RED ACCENT",
  "SIG": "LPO, SPOILER EXTENSION",
  "SL1": "LPO, PREMIUM INDOOR CAR COVER, RED WITH STINGRAY LOGO",
  "SL8": "LPO, REAR CORVETTE SCRIPT BADGE IN EDGE RED",
  "SL9": "LPO, ENGINE SPECIFICATION PLAQUE",
  "SLK": "LPO, REAR HATCH STRUT BRACKET, EDGE RED",
  "SLN": "LPO, VISIBLE CARBON FIBER ENGINE CROSS BRACE",
  "SNE": "LPO, JAKE HOOD GRAPHIC",
  "SNG": "LPO, FENDER HASH STRIPES, CARBON FLASH METALLIC WITH TECH BRONZE ACCENT",
  "SO1": "LPO, 70TH ANNIVERSARY SET OF PREMIUM LEATHER WEEKEND/TRAVEL BAGS",
  "SOA": "WHEELS, 20″ X 10″ (50.8 CM X 25.4 CM) FRONT AND 21″ X 13″ (53.3 CM X 33 CM) REAR SPIDER DESIGN, BLACK FORGED ALUMINUM",
  "SOC": "WHEELS, 20″ X 10″ (50.8 CM X 25.4 CM) FRONT AND 21″ X 13″ (53.3 CM X 33 CM) REAR SPIDER DESIGN, SATIN GRAPHITE FORGED ALUMINUM",
  "SOD": "WHEELS, 20″ X 10″ (50.8 CM X 25.4 CM) FRONT AND 21″ X 13″ (53.3 CM X 33 CM) REAR SPIDER DESIGN, MACHINED-FACE FORGED ALUMINUM",
  "SOE": "WHEELS, 20″ X 10″ (50.8 CM X 25.4 CM) FRONT AND 21″ X 13″ (53.3 CM X 33 CM) REAR SPIDER DESIGN, TITANIUM SATIN FORGED ALUMINUM",
  "SOF": "WHEELS, 20″ X 10″ (50.8 CM X 25.4 CM) FRONT AND 21″ X 13″ (53.3 CM X 33 CM) REAR 20-SPOKE, EDGE BLUE-PAINTED FORGED ALUMINUM",
  "SOG": "WHEELS, 20″ X 10″ (50.8 CM X 25.4 CM) FRONT AND 21″ X 13″ (53.3 CM X 33 CM) REAR 20-SPOKE, CARBON FLASH-PAINTED FORGED ALUMINUM",
  "SOH": "WHEELS, 20″ X 10″ (50.8 CM X 25.4 CM) FRONT AND 21″ X 13″ (53.3 CM X 33 CM) REAR 20-SPOKE, BRIGHT MACHINED FORGED ALUMINUM",
  "SOJ": "WHEELS, 20″ X 10″ (50.8 CM X 25.4 CM) FRONT AND 21″ X 13″ (53.3 CM X 33 CM) REAR 20-SPOKE, STERLING SILVER-PAINTED FORGED ALUMINUM",
  "SOM": "WHEELS, 20″ X 10″ (50.8 CM X 25.4 CM) FRONT AND 21″ X 13″ (53.3 CM X 33 CM) REAR BRIGHT POLISHED FORGED ALUMINUM",
  "SON": "WHEELS, 20″ X 10″ (50.8 CM X 25.4 CM) FRONT AND 21″ X 13″ (53.3 CM X 33 CM) REAR GLOSS BLACK FORGED ALUMINUM",
  "SOQ": "WHEELS, 20″ X 10″ (50.8 CM X 25.4 CM) FRONT AND 21″ X 13″ (53.3 CM X 33 CM) REAR SPIDER DESIGN, SATIN GRAPHITE FORGED ALUMINUM WITH RED STRIPE",
  "SPY": "LPO, BLACK LUG NUTS",
  "SPZ": "LPO, BLACK WHEEL LOCKS",
  "SQU": "LPO, ULTRA-HIGH SECURITY CHROME WHEEL LOCKS",
  "SRK": "WHEELS, 20″ X 10″ (50.8 CM X 25.4 CM) FRONT AND 21″ X 13″ (53.3 CM X 33 CM) REAR 10-SPOKE, PEARL NICKEL FORGED ALUMINUM",
  "SRN": "WHEELS, 20″ X 10″ (50.8 CM X 25.4 CM) FRONT AND 21″ X 13″ (53.3 CM X 33 CM) REAR 10-SPOKE, GLOSS BLACK FORGED ALUMINUM",
  "STE": "WHEELS, 20″ X 10″ (50.8 CM X 25.4 CM) FRONT AND 21″ X 13″ (53.3 CM X 33 CM) REAR 10-SPOKE, POLISHED FORGED ALUMINUM",
  "STI": "LPO, COMPOSITE ROCKER EXTENSIONS, BLACK",
  "STX": "WHEELS, 20″ X 10″ (50.8 CM X 25.4 CM) FRONT AND 21″ X 13″ (53.3 CM X 33 CM) REAR 10-SPOKE, BRIGHT POLISHED FORGED ALUMINUM WITH CARBON FLASH-PAINTED POCKETS",
  "STZ": "WHEELS, 20″ X 10″ (50.8 CM X 25.4 CM) FRONT AND 21″ X 13″ (53.3 CM X 33 CM) REAR VISIBLE CARBON FIBER WITH RED STRIPE",
  "SU1": "WHEELS, 20″ X 10″ (50.8 CM X 25.4 CM) FRONT AND 21″ X 13″ (53.3 CM X 33 CM) REAR 10-SPOKE, VISIBLE CARBON FIBER",
  "SUF": "LPO, E-RAY BADGES IN RAPID BLUE AND CARBON FLASH",
  "SXB": "LPO, SUEDE FRUNK AND TRUNK COMPARTMENT LINER",
  "SXR": "LPO, SUEDE FRUNK AND TRUNK COMPARTMENT LINER",
  "SXT": "LPO, SUEDE FRUNK AND TRUNK COMPARTMENT LINER",
  "T0A": "SPOILER, REAR, Z51",
  "T0E": "SPOILER, REAR",
  "T0F": "CARBON FIBER AERO PACKAGE, CARBON FLASH-PAINTED",
  "T0G": "CARBON FIBER AERO PACKAGE, VISIBLE",
  "T4L": "HEADLAMPS, LED",
  "TDM": "TEEN DRIVER",
  "TOM": "ZR1 CARBON FIBER AERO PACKAGE, VISIBLE CARBON FIBER",
  "TQ5": "INTELLIBEAM",
  "TR7": "HEADLAMP CONTROL, AUTOMATIC LEVELING SYSTEM",
  "TU7": "SEATS, TWO-TONE",
  "TVS": "LOW-PROFILE REAR SPOILER AND FRONT SPLITTER",
  "U2K": "SIRIUSXM WITH 360L",
  "U2L": "HD RADIO",
  "U5G": "5G VEHICLE CONNECTIVITY",
  "U80": "COMPASS, DIGITAL",
  "UD7": "REAR PARK ASSIST",
  "UDV": "GAUGE CLUSTER, 12″ DIAGONAL",
  "UE1": "ONSTAR SERVICES CAPABLE",
  "UE4": "FOLLOWING DISTANCE INDICATOR",
  "UEU": "FORWARD COLLISION ALERT",
  "UFG": "REAR CROSS TRAFFIC ALERT",
  "UFT": "SIDE BLIND ZONE ALERT",
  "UG1": "UNIVERSAL HOME REMOTE",
  "UHX": "LANE KEEP ASSIST WITH LANE DEPARTURE WARNING",
  "UHY": "AUTOMATIC EMERGENCY BRAKING",
  "UKT": "FRONT PEDESTRIAN AND BICYCLIST BRAKING",
  "UQH": "AUDIO SYSTEM FEATURE, BOSE PERFORMANCE SERIES SOUND SYSTEM",
  "UQS": "AUDIO SYSTEM FEATURE, BOSE PREMIUM 10-SPEAKER SYSTEM",
  "UQT": "PERFORMANCE DATA AND VIDEO RECORDER",
  "UQV": "NEAR FIELD COMMUNICATION (NFC)",
  "UTJ": "THEFT-DETERRENT SYSTEM",
  "UTU": "THEFT DETERRENT SENSOR, VEHICLE INCLINATION",
  "UTV": "THEFT DETERRENT SENSOR, VEHICLE INTERIOR MOVEMENT",
  "UV6": "HEAD-UP DISPLAY",
  "UVA": "HD FRONT AND REAR VISION CAMERAS",
  "UVB": "HD REAR VISION CAMERA",
  "V08": "COOLING SYSTEM, HEAVY-DUTY",
  "V8X": "LPO, VISIBLE CARBON FIBER SILL PLATES",
  "VHM": "VEHICLE HEALTH MANAGEMENT",
  "VK3": "LICENSE PLATE BRACKET, FRONT",
  "VPO": "LPO, JAKE C8.R REAR HASH GRAPHIC WITH TECH BRONZE ACCENT",
  "VPW": "LPO, JAKE C8.R REAR HASH GRAPHIC",
  "VQK": "LPO, CUSTOM SPLASH GUARDS",
  "VRZ": "LPO, PREMIUM INDOOR CAR COVER, BLACK, 70TH ANNIVERSARY",
  "VTB": "LPO, REAR FASCIA/ROOF STORAGE PROTECTOR",
  "VUP": "LPO, ENGINE BAY CLOSEOUT GRAPHICS",
  "VV4": "WI-FI HOTSPOT CAPABLE",
  "VW9": "LPO, TECH BRONZE WHEEL CENTER CAPS WITH CROSSED FLAGS LOGO",
  "VWD": "LPO, STINGRAY R LOGO WHEEL CENTER CAPS",
  "VWE": "LPO, FRONT RADIATOR GRILLE SCREENS",
  "VYW": "LPO, FLOOR MATS, PREMIUM CARPETED",
  "W2D": "LPO, CARGO NET SET",
  "WKQ": "LPO, PREMIUM INDOOR CAR COVER, BLACK WITH CROSSED FLAGS LOGO AND ACCESS PANELS",
  "WKR": "LPO, PREMIUM INDOOR CAR COVER, GT3.R, FULLY RENDERED",
  "WKS": "LPO, PREMIUM INDOOR CAR COVER, GALVANIZED COOL WITH Z06 LOGO",
  "WL0": "LPO, PREMIUM INDOOR CAR COVER, GRAY, FULLY RENDERED C8.R",
  "XFN": "TIRES, 245/35ZR19 FRONT AND 305/30ZR20 REAR, BLACKWALL, ALL-SEASON, PERFORMANCE",
  "XFQ": "TIRES, 245/35ZR19 FRONT AND 305/30ZR20 REAR, BLACKWALL, HIGH PERFORMANCE",
  "XFR": "TIRES, 275/30ZR20 FRONT AND 345/25ZR21 REAR, BLACKWALL, HIGH PERFORMANCE",
  "XFS": "TIRES, 275/30ZR20 FRONT AND 345/25ZR21 REAR, BLACKWALL, MICHELIN PILOT SPORT CUP 2 R ULTRA PERFORMANCE",
  "XFT": "TIRES, 275/30ZR20 FRONT AND 345/25ZR21 REAR, ALL-SEASON, BLACKWALL, PERFORMANCE",
  "Y70": "70TH ANNIVERSARY SPECIAL EDITION",
  "YF5": "EMISSIONS, CALIFORNIA STATE REQUIREMENTS",
  "Z07": "Z07 PERFORMANCE PACKAGE",
  "Z51": "Z51 PERFORMANCE PACKAGE",
  "ZER": "ZER PERFORMANCE PACKAGE",
  "ZF1": "AERO DELETE",
  "ZTK": "ZTK TRACK PERFORMANCE PACKAGE",
  "ZYC": "CARBON FLASH METALLIC-PAINTED OUTSIDE MIRRORS AND SPOILER (WHEN EQUIPPED)",
  "ZZ3": "CONVERTIBLE ENGINE APPEARANCE PACKAGE",
}

module.exports = {
  colorMap,
  intColor,
  seatCode,
  mmc,
  camaroRpo,
  corvetteRpo
}
