const colorMap = {
    "ARGENT SILVER METALLIC": "GXD",
    "BLACK": "GBA",
    "BLACK DIAMOND TRICOAT": "GLK",
    "BLACK RAVEN": "GBA",
    "BLAZE METALLIC": "GCF",
    "COASTAL BLUE METALLIC": "GJV",
    "CRUSH": "G16",
    "CRYSTAL WHITE TRICOAT": "G1W",
    "CYBER YELLOW METALLIC": "GCP",
    "DARK EMERALD FROST": "G7W",
    "DARK MOON METALLIC": "GLU",
    "ELECTRIC BLUE": "GMO",
    "EVERGREEN METALLIC": "GJ0",
    "GARNET METALLIC": "GLR",
    "GARNET RED TINTCOAT": "G7E",
    "INFRARED TINTCOAT": "GSK",
    "MAVERICK NOIR FROST": "GNW",
    "MERCURY SILVER METALLIC": "GKA",
    "MIDNIGHT SKY METALLIC": "GXE",
    "MIDNIGHT STEEL METALLIC": "GXU",
    "NITRO YELLOW METALLIC": "GCP",
    "PANTHER BLACK MATTE": "GNW",
    "PANTHER BLACK METALLIC": "GLK",
    "RADIANT RED TINTCOAT": "GNT",
    "RALLY GREEN METALLIC": "GJ0",
    "RAPID BLUE": "GMO",
    "RED HOT": "G7C",
    "RED OBSESSION TINTCOAT": "G7E",
    "RIFT METALLIC": "GRW",
    "RIPTIDE BLUE METALLIC": "GJV",
    "RIVERSIDE BLUE METALLIC": "GKK",
    "ROYAL SPICE METALLIC": "GLL",
    "SATIN STEEL GREY METALLIC": "G9K",
    "SATIN STEEL METALLIC": "G9K",
    "SHADOW GRAY METALLIC": "GJI",
    "SHADOW METALLIC": "GJI",
    "SHARKSKIN METALLIC": "GXD",
    "SHOCK": "GKO",
    "SUMMIT WHITE": "GAZ",
    "VELOCITY RED": "G7C",
    "VIVID ORANGE METALLIC": "GCF",
    "WAVE METALLIC": "GKK",
    "WILD CHERRY TINTCOAT": "GSK"
};

mmc = {
    "1AG37": "1LT",
    "1AG37": "1LS",
    "1AG67": "1LT",
    "1AH37": "2LT",
    "1AH37": "3LT",
    "1AH67": "2LT",
    "1AH67": "3LT",
    "1AJ37": "LT1",
    "1AJ37": "1SS",
    "1AJ67": "LT1",
    "1AJ67": "1SS",
    "1AK37": "2SS",
    "1AK67": "2SS",
    "1AL37": "1SE",
    "1AL67": "1SE",
    "6DB69": "1SB", // CT4 LUXURY
    "6DB79": "1SB", // CT5 LUXURY
    "6DC69": "1SD", // CT4 PREMIUM LUXURY
    "6DC79": "1SD", // CT5 PREMIUM LUXURY
    "6DD69": "1SE", // CT4 SPORT
    "6DD79": "1SE", // CT5 SPORT
    "6DE69": "1SF", // CT4 V-SERIES
    "6DE79": "1SF", // CT5 V-SERIES
    "6DF69": "1SP", // CT4 V-SERIES BLACKWING
    "6DF79": "1SV" // CT5 V-SERIES BLACKWING
};

module.exports = {
    colorMap,
    mmc
}
