const colorMap = {
  "ROSWELL GREEN METALLIC": "G4Z",
  "BAEGE METALLIC": "BAEGE METALLIC",
  "COPPERTINO METALLIC": "COPPERTINO METALLIC",
  "ABALONE WHITE": "ABALONE WHITE",
  "SEYCHELLES METALLIC": "SEYCHELLES METALLIC",
  "SEEKER METALLIC": "SEEKER METALLIC",
  "KIMONO METALLIC": "KIMONO METALLIC",
  "CHARTREUSE METALLIC": "CHARTREUSE METALLIC",
  "CHARTREUSE MATTE": "CHARTREUSE MATTE",
  "HIGH VOLTAGE TINT": "HIGH VOLTAGE TINT",
  "TACTICAL TINT": "TACTICAL TINT",
  "HYPERSONIC METALLIC": "HYPERSONIC METALLIC",
  "BARB WIRE": "BARB WIRE",
  "BLACK MEETS KETTLE": "BLACK MEETS KETTLE",
  "ACCELERATE YELLOW METALLIC": "GD0",
  "AMPLIFY ORANGE TINTCOAT": "GC5",
  "CORVETTE RACING YELLOW TINTCOAT": "GC6",
  "ARCTIC WHITE": "G8G",
  "ARGENT SILVER METALLIC": "GXD",
  "BLACK DIAMOND TRICOAT": "GLK",
  "BLACK RAVEN": "GBA",
  "BLACK": "GBA",
  "BLADE SILVER METALLIC": "GAN",
  "BLAZE ORANGE METALLIC": "GCF",
  "CACTI GREEN": "GVR",
  "CAFFEINE METALLIC": "G48",
  "CARBON FLASH METALLIC": "GAR",
  "CERAMIC MATRIX GRAY METALLIC": "G9F",
  "COASTAL BLUE METALLIC": "GJV",
  "COMPETITION YELLOW TINTCOAT": "GBK",
  "CRUSH": "G16",
  "CRYSTAL WHITE TRICOAT": "G1W",
  "CYBER YELLOW METALLIC": "GCP",
  "DARK EMERALD FROST": "G7W",
  "DARK MOON METALLIC": "GLU",
  "DEEP SPACE METALLIC": "GAI",
  "ELECTRIC BLUE": "GMO",
  "ELKHART LAKE BLUE METALLIC": "GS7",
  "EVERGREEN METALLIC": "GJ0",
  "GARNET METALLIC": "GLR",
  "GARNET RED TINTCOAT": "G7E",
  "HYPERSONIC GRAY METALLIC": "GA7",
  "HYSTERIA PURPLE METALLIC": "GXL",
  "INFRARED TINTCOAT": "GSK",
  "LONG BEACH RED METALLIC TINTCOAT": "G1E",
  "MANHATTAN NOIR METALLIC": "GCI",
  "MAVERICK NOIR FROST": "GNW",
  "MERCURY SILVER METALLIC": "GKA",
  "MIDNIGHT SKY METALLIC": "GXF",
  "MIDNIGHT STEEL METALLIC": "GXU",
  "NITRO YELLOW METALLIC": "GCP",
  "PANTHER BLACK MATTE": "GNW",
  "PANTHER BLACK METALLIC TINTCOAT": "GLK",
  "RADIANT RED TINTCOAT": "GNT",
  "RADIANT SILVER METALLIC": "GAN",
  "RALLY GREEN METALLIC": "GJ0",
  "RAPID BLUE": "GMO",
  "RED HORIZON TINTCOAT": "GPJ",
  "RED HOT": "G7C",
  "RED MIST METALLIC TINTCOAT": "GPH",
  "RED OBSESSION TINTCOAT": "G7E",
  "RIFT METALLIC": "GRW",
  "RIPTIDE BLUE METALLIC": "GJV",
  "RIVERSIDE BLUE METALLIC": "GKK",
  "ROYAL SPICE METALLIC": "GLL",
  "SATIN STEEL GRAY METALLIC": "G9K",
  "SATIN STEEL METALLIC": "G9K",
  "SEA WOLF GRAY TRICOAT": "GXA",
  "SEBRING ORANGE TINTCOAT": "G26",
  "SHADOW GRAY METALLIC": "GJI",
  "SHADOW METALLIC": "GJI",
  "SHARKSKIN METALLIC": "GXD",
  "SHOCK": "GKO",
  "SILVER FLARE METALLIC": "GSJ",
  "STELLAR BLACK METALLIC": "GB8",
  "SUMMIT WHITE": "GAZ",
  "TORCH RED": "GKZ",
  "TYPHOON METALLIC": "GBW",
  "VELOCITY RED": "G7C",
  "VIVID ORANGE METALLIC": "GCF",
  "WAVE METALLIC": "GKK",
  "WHITE PEARL METALLIC TRICOAT": "G1W",
  "WILD CHERRY TINTCOAT": "GSK",
  "ZEUS BRONZE METALLIC": "GUI",
  "SILVER ICE METALLIC": "GAN",
  "MOSAIC BLACK METALLIC": "GB8",
  "WATKINS GLEN GRAY METALLIC": "G7Q",
  "ADMIRAL BLUE METALLIC": "GTR",
  "INTERSTELLAR WHITE": "GAZ",
  "VOID BLACK": "GBA",
  "METEORITE METALLIC": "GNO",
  "DEEP AURORA METALLIC": "GXN",
  "AFTERBURNER TINTCOAT": "GC5",
  "TIDE METALLIC": "G7X",
  "SUPERNOVA METALLIC": "GKK",
  "NEPTUNE BLUE MATTE": "GLG",
  "SOLAR ORANGE": "GAG",
  "GRAPHITE BLUE METALLIC": "GAI",
  "MOONSHOT GREEN MATTE": "G7W",
  "COASTAL DUNE": "G42",
  "MAGNUS GRAY MATTE": "GBL",
  "AUBURN MATTE": "GNR",
  "BLUE SMOKE METALLIC": "GAI",
  "SLATE GRAY METALLIC": "GNO",
  "HABANERO ORANGE": "GAG",
  "ZEPHYR BLUE MATTE METALLIC": "GLG",
  "DARK EMBER TINTCOAT": "GAB",
  "DEEP OCEAN METALLIC": "GAI",
  "ONYX BLACK": "GBA",
  "MOONLIGHT MATTE": "GLG",
  "GLACIER WHITE TRICOAT": "G4J",
  "DEEP BRONZE METALLIC": "GXN",
  "THUNDERSTORM GRAY": "GNO",
  "SANDSTONE": "G42",
  "VIBRANT WHITE TRICOAT": "G4J",
  "BLACK CHERRY TINTCOAT": "GAB",
  "MONARCH ORANGE": "GAG",
  "MAGNUS METAL FROST": "GBL",
  "LUNA METALLIC": "GNO",
  "ADOBE FROST": "GNR",
  "FLARE METALLIC": "GSJ",
  "MIDNIGHT STEEL FROST": "GLG",
};

const intColor = {
  // Corvette
  // - C7
  "141": "Gray Perforated Mulan Leather",
  "143": "Gray Perforated Mulan Leather",
  "144": "Gray Leather w/ Sueded Microfiber Inserts",
  "145": "Gray Perforated Napa Leather",
  "146": "Gray Leather w/ Sueded Microfiber Inserts",
  "191": "Jet Black Perforated Mulan Leather",
  "192": "Jet Black Leather w/ Sueded Microfiber Inserts",
  "193": "Jet Black Perforated Mulan Leather",
  "194": "Jet Black Leather w/ Sueded Microfiber Inserts",
  "195": "Jet Black Perforated Napa Leather",
  "196": "Jet Black Leather w/ Sueded Microfiber Inserts",
  "198": "Jet Black Leather w/ Sueded Microfiber Inserts",
  "343": "Kalahari Perforated Mulan Leather",
  "344": "Kalahari Leather w/ Sueded Microfiber Inserts",
  "345": "Kalahari Perforated Napa Leather",
  "346": "Kalahari Leather w/ Sueded Microfiber Inserts",
  "701": "Adrenaline Red Perforated Mulan Leather",
  "703": "Adrenaline Red Perforated Mulan Leather",
  "704": "Adrenaline Red Leather w/ Sueded Microfiber Inserts",
  "705": "Adrenaline Red Perforated Napa Leather",
  "706": "Adrenaline Red Leather w/ Sueded Microfiber Inserts",
  "755": "Spice Red Perforated Mulan Leather",
  "000": "Jet Black w/ Orange Stitching Leather w/ Sueded Microfiber Inserts",
  // - C8
  "HTA": "Jet Black Mulan Leather w/ Perforated Inserts",
  "HTE": "Jet Black Napa Leather w/ Perforated Inserts",
  "HTJ": "Jet Black Performance Textile",
  "HTO": "Tension W/ Twilight Blue Dipped Napa Leather w/ Perforated Inserts",
  "HU1": "Sky Cool Gray Napa Leather w/ Perforated Inserts",
  "HU2": "Adrenaline Red Napa Leather w/ Perforated Inserts",
  "HU3": "Morello Red Dipped Napa Leather w/ Perforated Inserts",
  "HUE": "Natural Napa Leather w/ Perforated Inserts",
  "HUP": "Sky Cool Gray Mulan Leather w/ Perforated Inserts",
  "HUQ": "Adrernaline Red Mulan Leather w/ Perforated Inserts",
  "HUR": "Adrernaline Red Mulan Leather w/ Perforated Inserts",
  "HUL": "Adrernaline Red NAPA Leather w/ Perforated Inserts",
  "HU7": "Adrernaline Red NAPA Leather w/ Perforated SUEDED MICROFIBER Inserts",
  "HUA": "Adrernaline Red NAPA Leather w/ Perforated SUEDED MICROFIBER Inserts",
  "HZN": "Natural Dipped Napa Leather w/ Perforated Inserts",
  "HTM": "JET BLACK NAPA LEATHER W/ PERFORATED INSERTS",
  "HTP": "JET BLACK NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  "HTT": "JET BLACK NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  "HUN": "SKY COOL GRAY MULAN LEATHER W/ PERFORATED INSERTS",
  "HUK": "SKY COOL GRAY NAPA LEATHER W/ PERFORATED INSERTS",
  "HU6": "SKY COOL GRAY NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  "HU9": "SKY COOL GRAY NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  "HUV": "NATURAL MULAN LEATHER W/ PERFORATED INSERTS",
  "HTN": "NATURAL NAPA LEATHER W/ PERFORATED INSERTS",
  "HTQ": "NATURAL NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  "HTG": "NATURAL NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  "HUF": "NATURAL DIPPED NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  "HT7": "SKY COOL GRAY W/ STRIKE YELLOW NAPA LEATHER W/ PERFORATED INSERTS",
  "HFC": "SKY COOL GRAY W/ STRIKE YELLOW NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  "HNK": "ADDRENALINE RED DIPPED NAPA LEATHER W/ PERFORATED INSERTS",
  "HV1": "CERAMIC WHITE W/ RED STITCHING NAPA LEATHER W/ PERFORATED INSERTS",
  "HV2": "ARTEMIS NAPA LEATHER W/ PERFORATED INSERTS",
  "HUX": "HABANERO NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  "HUW": "HABANERO NAPA LEATHER W/ PERFORATED INSERTS",
  "HZB": "CUSTOM SKY COOL GRAY W/ JET BLACK ACCENTS NAPA LEATHER W/ PERFORATED INSERTS",
  "HVT": "CUSTOM SKY COOL GRAY W/ JET BLACK ACCENTS NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  "HVV": "CUSTOM JET BLACK W/ SKY COOL GRAY ACCENTS NAPA LEATHER W/ PERFORATED INSERTS",
  "HMO": "CUSTOM JET BLACK W/ SKY COOL GRAY ACCENTS NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  "HUU": "CUSTOM ADRENALINE RED W/ JET BLACK ACCENTS NAPA LEATHER W/ PERFORATED INSERTS",
  "HZP": "CUSTOM ADRENALINE RED W/ JET BLACK ACCENTS NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  "HU0": "CUSTOM JET BLACK W/ ADRENALINE RED ACCENTS NAPA LEATHER W/ PERFORATED INSERTS",
  "HXO": "CUSTOM JET BLACK W/ ADRENALINE RED ACCENTS NAPA LEATHER W/ PERFORATED SUEDED MICROFIBER INSERTS",
  // Camaro
  "H01": "Kalahari Leather",
  "H0W": "Jet Black Leather W/ Red accents",
  "H0Y": "Jet Black Leather",
  "H13": "Ceramic White Leather",
  "H16": "Adrenaline Red Leather",
  "H17": "Medium Ash Gray Leather",
  "H1T": "Jet Black Cloth",
  "H72": "Medium Ash Gray Cloth",
  // Cadillac
  "E2B": "Jet Black W/ Signet Accents Leather w/ Mini-Perforated Custom Quilted Inserts and Sueded Front Seatbacks",
  "E2D": "Jet Black W/ Adrenaline Red Accents Leather w/ Mini-Perforated Custom Quilted Inserts and Sueded Front Seatbacks",
  "E2G": "Jet Black W/ Sky Cool Gray Accents Leather w/ Mini-Perforated Custom Quilted Inserts and Sueded Front Seatbacks",
  "H0L": "Sangria W/ Jet Black Accents Leather w/ Mini-Perforated Inserts",
  "H0M": "Cinnamon W/ Jet Black Accents Leather w/ Mini-Perforated Inserts",
  "H1Y": "Jet Black W/ Jet Black Accents Leather w/ Mini-Perforated Inserts",
  "H2G": "Jet Black W/ Jet Black Accents Inteluxe",
  // UNSURE "H2X": "JET BLACK LEATHER W/ CHEVRON PERFORATED INSERTS",
  "H2X": "Jet Black W/ Jet Black Accents Leather w/ Mini-Perforated Inserts",
  "H66": "JET BLACK LEATHER",
  "HAV": "Maple Sugar W/ Jet Black Accents Leather w/ Mini-Perforated Inserts",
  "HBE": "Jet Black W/ Jet Black Accents Leather/Performance Cloth/Sueded Microfiber/Ineluxe and Sueded Front Seatbacks",
  "HBF": "Natural Tan W/ Jet Black Accents Leather w/ Mini-Perforated Custom Quilted Inserts and Sueded Front Seatbacks",
  "HEA": "Jet Black W/ Jet Black Accents Leather w/ Sueded Front Seatbacks",
  "HEB": "Sky Cool Gray W/ Jet Black Accents Leather w/ Sueded Front Seatbacks",
  "HGM": "Jet Black W/ Jet Black Accents Leather w/ Mini-Perforated Inserts",
  "HIK": "Sahara Beige W/ Jet Black Accents Leather w/ Mini-Perforated Inserts",
  "HIT": "Sahara Beige W/ Jet Black Accents Inteluxe",
  "HIZ": "SEMI-ANILINE LEATHER W/ CHEVRON PERFORATED INSERTS",
  "HJC": "Natural Tan W/ Jet Black Accents Full Semi-Aniline Leather w/ Mini-Perforated Inserts: Custom Quilting and Carbon Fiber Front Seatbacks",
  "HJD": "Sky Cool Gray W/ Jet Black Accents Full Semi-Aniline Leather w/ Mini-Perforated Inserts: Custom Quilting and Carbon Fiber Front Seatbacks",
  "HK1": "VERY LIGHT CASHMERE W/ MAPLE SUGAR ACCENTS SEMI-ANILINE LEATHER W/ CHEVRON PERFORATED INSERTS",
  "HMC": "Whisper Beige W/ Jet Black Accents Inteluxe",
  "HMQ": "SAHARA BEIGE W/ JET BLACK ACCENTS LEATHER W/ CHEVRON PERFORATED INSERTS",
  "HMR": "Jet Black W/ Jet Black Accents Full Semi-Aniline Leather w/ Mini-Perforated Inserts: Custom Quilting and Carbon Fiber Front Seatbacks",
  "HNC": "Whisper Beige W/ Jet Black Accents Leather w/ Mini-Perforated Inserts",
  "HND": "Whisper Beige W/ Jet Black Accents Leather w/ Mini-Perforated Inserts",
  "HTX": "DARK AUBURN W/ JET BLACK ACCENTS LEATHER W/ CHEVRON PERFORATED INSERTS",
  "HTZ": "SAHARA BEIGE W/ JET BLACK ACCENTS LEATHER",
  "HXR": "Jet Black W/ Jet Black Accents Inteluxe",
  "HZK": "Sedona Sauvage W/ Jet Black Accents Semi-Aniline Full Leather w/ Chevron Perforated Inserts",
  "HZQ": "Jet Black W/ Jet Black Accents Inteluxe",
  "EG1": "Sky Cool Gray W/ Santorini Blue Accents Leather W/ Mini-Perforated Custom Quilted Inserts and Sueded Front Seatbacks",
  "E54": "Jet Black W/ Phantom Blue Accents Leather W/ Mini-Perforated Custom Quilted Inserts and Sueded Front Seatbacks",
  "H9F": "Jet Black Evotex",
  "EMX": "Black Evotex",
  // ESCALADE IQ
  "ENB": "SHEER GRAY W/ DARK MEDIUM CINDER ACCENTS INTELUXE W/ FJORD (CHEVRON) QUILTING PATTERN",
  "EMY": "CAMELIA W/ BACKEN BLACK ACCENTS NOUVEAULUXE W/ EVREN (BACK INSERTS) AND CYGUS (SEAT CUSHION) PERFORATED PATTERN",
  "ENK": "HARBOR BLUE W/ BACKEN BLACK ACCENTS NOUVEAULUXE W/ CARRINGTON FALLS PERFORATED PATTERN",
  // Hummer EV
  "H9Z": "LUNAR HORIZON (JET BLACK/LIGHT GREY) Premium Leather-Alternative",
  "HAS": "LUNAR SHADOW (JET BLACK/TAUPE) Premium Leather-Alternative",
  "HBZ": "GRANITE DRIFT PREMIUM LEATHER-ALTERNATIVE",
  "HR5": "STEALTH ECLIPSE PREMIUM LEATHER-ALTERNATIVE",
  "EHM": "VELOCITY EMBER PREMIUM LEATHER-ALTERNATIVE",
  // Silverado EV
  "H7D": "Black Evotex",
  //"H7D": "BACKEN BLACK W/ SANTORINI ACCENTS INTELUXE W/ FJORD (CHEVRON) QUILTING PATTERN", ESCALADE IQ
  "EMW": "Black w/ Sky Cool Gray Evotex",
  // Sierra EV
  "E4V": "After Dark (Black) Premium Leather alternative",
  "EWA": "Desert Dune Premium Leather alternative",
  "EH7": "AFTER DARK (BLACK) CORETEC",
  "EH9": "FOREST STORM CORETEC",
  "HCN": "Black Evotex",
  "EB9": "Black w/ Artemis Evotex",
};

const seatCode = {
  // Camaro
  "A50": "Sport front buckets",
  "AQJ": "RECARO Performance front buckets",
  // Corvette
  "AQ9": "GT1 buckets",
  "AE4": "Competition buckets",
  "AH2": "GT2 / Competition buckets",
  // Cadillac
  "": "",
  // Silverado EV
  "AR9": "Front Bucket Seats",
  // Hummer EV
  "A50": "Front bucket seats with center console",
};

const mmc = {
  // Camaro
  "1AG37": "1LT",
  "1AG67": "1LT",
  "1AH37": "2LT",
  "1AH67": "2LT",
  "1AJ37": "1SS",
  "1AJ67": "1SS",
  "1AK37": "2SS",
  "1AK67": "2SS",
  "1AL37": "1SE",
  "1AL67": "1SE",
  // Corvette SR C7
  "1YY07": "", // Coupe
  "1YY67": "", // Conv
  // Corvette GS C7
  "1YW07": "", // Coupe
  "1YW67": "", // Conv
  // Corvette SR Z51 C7
  "1YX07": "", // Coupe
  "1YX67": "", // Conv
  // Corvette Z06 C7
  "1YZ07": "", // Coupe
  "1YZ67": "", // Conv
  // Corvette ZR1 C7
  "1YV07": "", // Coupe
  "1YV67": "", // Conv
  // Corvette C8
  "1YC07": "", // Coupe
  "1YC67": "", // Conv
  // Corvette Z06 C8
  "1YH07": "", // Coupe
  "1YH67": "", // Conv
  // Corvette E-Ray C8
  "1YG07": "", // Coupe
  "1YG67": "", // Conv
  // Corvette ZR1 C8
  "1YR07": "", // Coupe
  "1YR67": "", // Conv
  // Cadillac
  "6DB69": "1SB", // CT4 LUXURY
  "6DB79": "1SB", // CT5 LUXURY
  "6DC69": "1SD", // CT4 PREMIUM LUXURY
  "6DC79": "1SD", // CT5 PREMIUM LUXURY
  "6DD69": "1SE", // CT4 SPORT
  "6DD79": "1SE", // CT5 SPORT
  "6DE69": "1SF", // CT4 V-SERIES
  "6DE79": "1SF", // CT5 V-SERIES
  "6DF69": "1SP", // CT4 V-SERIES BLACKWING
  "6DF79": "1SV", // CT5 V-SERIES BLACKWING
  "6KM69": "1SP", // CT6 PLATINUM
  "6KH69": "1SB", // CT6 LUXURY
  "6KJ69": "1SD", // CT6 PREMIUM LUXURY
  "6KN69": "1SV", // CT6 V-SERIES
  // Hummer EV
  "TT35526": "", // SUV
  "TT35743": "", // Pickup
  // Silverado EV
  "CT35843": "",
  // Sierra EV
  "TT35843": "",
};

const camaroRpo = {
  "2F5": "Knee pads, Red",
  "3DL": "Interior trim, carbon fiber instrument panel molding",
  "3F9": "Seat belt color, Red",
  "56H": "LPO, SS 20\" (50.8 cm) 5-spoke gloss Black wheels with Red stripe",
  "56M": "LPO, SS 20\" (50.8 cm) 5-split spoke machined-face wheels",
  "56R": "Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear 5-split spoke premium Gray-painted machined-face aluminum",
  "56S": "Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear bright 5-spoke Silver-painted aluminum",
  "56V": "Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear 5-spoke Carbon Flash painted aluminum",
  "56W": "Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear 5-split spoke bright Silver-painted aluminum",
  "56Z": "Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear 5-split spoke Black forged aluminum",
  "57S": "LPO, SS 20\" (50.8 cm) 5-split spoke Satin Black wheels",
  "57W": "Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear 5-split spoke polished forged aluminum with Black star center cap",
  "58E": "Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear Black-painted aluminum with Red accents",
  "5JX": "LPO, LT 20\" (50.8 cm) 5-split spoke Satin Black wheels",
  "5KP": "LPO, Illuminated sill plates",
  "5LQ": "LPO, 6 Piston Front Brake Kit",
  "5V5": "LPO, Body-color high-wing spoiler",
  "5VF": "LPO, Carbon fiber exhaust tip",
  "5VM": "LPO, Ground Effects Package",
  "5WF": "LPO, Battery Protection Package",
  "5YN": "LPO, Carbon Fiber-look shift knob (auto) or Carbon Fiber-look shift knob medallion (manual)",
  "5ZB": "LPO, Camaro logo wheel center caps",
  "5ZD": "LPO, Wheel center caps",
  "5ZU": "LPO, Body-color blade spoiler",
  "5ZV": "LPO, Satin Black blade spoiler",
  "5ZW": "LPO, Satin Black wing spoiler",
  "5ZZ": "LPO, Carbon Flash Metallic blade spoiler",
  "62O": "LPO, Clear CHMSL (Center High Mount Stop Lamp)",
  "A1Y": "SS 1LE Track Performance Package",
  "A1Z": "ZL1 1LE Extreme Track Performance Package",
  "A45": "Memory Package",
  "A50": "Seats, front Sport bucket",
  "A9B": "Satin Black Appearance Package",
  "AKQ": "Seat adjuster, front passenger, 6-way power",
  "AM7": "Seat, rear, folding",
  "AQJ": "Seats, front bucket, RECARO performance",
  "ATH": "Keyless Open and Start",
  "AV3": "Seat adjuster, driver, 8-way power",
  "B7G": "Sill plates, illuminated",
  "B9M": "Tail lamps, dark tint",
  "BO3": "White Pearl Rally Stripes",
  "BO4": "Black Metallic Rally Stripes",
  "BRD": "Ceramic White Interior Package",
  "BRJ": "Adrenaline Red Interior Package",
  "BTV": "Remote vehicle starter system",
  "C2U": "Silver Rally Stripes",
  "C3O": "Black Rally Stripes",
  "C70": "Lighting, interior spectrum",
  "CF5": "Sunroof, power",
  "CFW": "Hood insert, visible Carbon Fiber weave",
  "CG3": "Emblem, Black Camaro fender badge",
  "CG6": "Emblem, Black Camaro fender badge with Red outline",
  "CJ2": "Air conditioning, dual-zone automatic climate control",
  "D5S": "Spoiler, rear, blade, Satin Black",
  "D5Z": "Spoiler, rear, stanchion",
  "D80": "Spoiler, decklid-mounted lip spoiler",
  "D88": "1LE Hash Mark Decal",
  "DRZ": "Rear Camera Mirror",
  "DSM": "Hood wrap, Satin Black",
  "DUU": "Black Center Stripe",
  "DUV": "Silver Center Stripe",
  "DVV": "Black Metallic Center Stripe",
  "DW7": "White Pearl Center Stripe",
  "DW8": "Black Metallic Center Stripe",
  "F55": "Magnetic Ride Control",
  "FTJ": "Front splitter",
  "G96": "Differential, electronic limited-slip",
  "IOS": "Audio system, Chevrolet Infotainment 3 Plus system, 8\" diagonal HD color touchscreen",
  "IOT": "Audio system, Chevrolet Infotainment 3 Premium system with connected Navigation, 8\" diagonal HD color touchscreen",
  "J55": "Brakes, Brembo 4-piston front, performance, 4-wheel antilock, 4-wheel disc",
  "J6F": "Calipers, Red",
  "J6G": "Brakes, Brembo 4-piston front and rear, performance, 4-wheel antilock, 4-wheel disc",
  "J6H": "Brakes, Brembo 6-piston front and 4-piston rear, performance",
  "J6L": "Calipers, Orange",
  "J6M": "Brakes, Brembo Red, 6-piston front monobloc calipers, 4-piston rear calipers, 2-piece rotors, performance",
  "JF5": "Pedals, sport alloy",
  "K4C": "Wireless Charging",
  "KA1": "Seats, heated driver and front passenger",
  "KB7": "Paddle-shift manual controls",
  "KQV": "Seats, ventilated driver and front passenger",
  "KS9": "Shift knob, sueded microfiber-wrapped",
  "KTI": "Tire inflation kit",
  "MN6": "Transmission, 6-speed manual",
  "MX0": "Transmission, 10-speed automatic",
  "N26": "Steering wheel, 3-spoke, sueded microfiber-wrapped, flat-bottom",
  "NPP": "Exhaust, dual-mode",
  "P3H": "Bowties, Black, front and rear",
  "PCJ": "LPO, Dark Tint Rear Lighting Package",
  "PCK": "LPO, Black Accent Exterior Package",
  "PCL": "LPO, Black Wheel Lug Nuts and Locks Package",
  "PCR": "LPO, Satin Black Front Splitter/Side Rockers Package",
  "PCY": "LPO, Red Accent Exterior Package",
  "PDL": "Design Package 1",
  "PDN": "Design Package 2",
  "PDP": "Design Package 3",
  "PDY": "LPO, Body-Color Spoiler with Wicker Package",
  "PKJ": "Wheels, 19\" x 11\" (48.3 cm x 27.9 cm) front and 19\" x 12\" (48.3 cm x 30.48 cm) rear low gloss Black-painted forged aluminum",
  "Q7G": "Wheels, 20\" (50.8 cm) 5-split spoke Black forged aluminum",
  "R88": "LPO, Front illuminated and rear non-illuminated bowtie emblems in Black",
  "REG": "Wheels, 18\" (45.7 cm) Silver-painted aluminum",
  "RIN": "LPO, Camaro logo fender badge",
  "RMH": "LPO, Front splitter, Carbon Flash Metallic",
  "RNX": "LPO, Outdoor vehicle cover",
  "RO1": "LPO, Black lower grille with Silver-painted inserts",
  "RO2": "LPO, Black lower grille with Gloss Black inserts",
  "RQ9": "Wheels, 20\" (50.8 cm) 5-split spoke premium Gray-painted, machined-face aluminum",
  "RQA": "Wheels, 20\" (50.8 cm) Silver-painted aluminum",
  "RSK": "Wheels, 20\" x 10\" (50.8 cm x 25.4 cm) front and 20\" x 11\" (50.8 cm x 27.9 cm) rear Satin Graphite forged aluminum",
  "RTH": "Wheels, 20\" (50.8 cm) 5-spoke Carbon Flash painted aluminum",
  "RTJ": "Wheels, 20\" (50.8 cm) 5-spilt spoke bright Silver-painted aluminum",
  "RTQ": "Wheels, 20\" x 10\" (50.8 cm x 25.4 cm) front and 20\" x 11\" (50.8 cm x 27.9 cm) rear Dark Graphite premium paint, forged aluminum",
  "RWH": "LPO, Indoor vehicle cover",
  "RWJ": "LPO, Outdoor vehicle cover",
  "RXH": "LPO, Silver RS wheel center caps",
  "RXJ": "LPO, Silver SS wheel center caps",
  "RY2": "LPO, Black Metallic Hash Mark Stripes",
  "RZ3": "LPO, Front splitter",
  "RZB": "LPO, Black lower grille with Red Hot inserts",
  "S0O": "LPO, Illuminated footwells",
  "S0U": "LPO, Black sueded knee pads",
  "S0V": "LPO, White knee pads",
  "SA7": "LPO, Suede shift knob and boot kit",
  "SB2": "LPO, Carbon Flash Metallic wing spoiler",
  "SB3": "LPO, ZL1 SPEC rear spoiler, body-color",
  "SB7": "LPO, Red Spider Stripes",
  "SB9": "LPO, Satin Black Spider Stripes",
  "SCG": "LPO, 6.2L Strut tower brace in Black",
  "SF8": "LPO, Silver Body-Side Spear Stripes",
  "SF9": "LPO, Blue Hash Mark Stripes",
  "SFC": "LPO, White Pearl Hash Mark Stripes",
  "SFE": "LPO, Wheel locks",
  "SH1": "LPO, Embroidered center console lid with Camaro badge",
  "SH2": "LPO, Embroidered center console lid",
  "SHL": "LPO, 20\" (50.8 cm) 5-spoke gloss Black wheels with Red outline stripe",
  "SHQ": "LPO, Silver Hash Mark Stripes",
  "SHS": "LPO, Satin Black Hood Stripe with Silver Ice Metallic Hash Mark",
  "SHU": "LPO, Satin Black Hood Stripe with Red Hot Hash Mark",
  "SIA": "LPO, Wicker bill",
  "SIB": "LPO, Interior spectrum lighting, Dark Night",
  "SIC": "LPO, Interior spectrum lighting, Red Day, Satin Red and Gloss Red pattern finish",
  "SJ8": "LPO, Interior spectrum lighting, Structura",
  "SKW": "LPO, 20\" (50.8 cm) 5-split spoke machined-face wheels",
  "SL1": "LPO, Indoor vehicle cover",
  "SL2": "LPO, Front splitter",
  "SLN": "LPO, Strut tower brace",
  "SNB": "LPO, Silver Spider Stripes",
  "SNC": "LPO, White Pearl Spider Stripes",
  "SNE": "LPO, Silver Stinger Stripe",
  "SNG": "LPO, Red Hash Mark Stripes",
  "SNH": "LPO, White Pearl Body-Side Spear Stripes",
  "SNJ": "LPO, Satin Black Stinger Stripe",
  "SNM": "LPO, White Pearl Stinger Stripe",
  "SNP": "LPO, Red Body-Side Spear Stripes",
  "SNQ": "LPO, Gray Body-Side Spear Stripes",
  "SNS": "LPO, Blue Body-Side Spear Stripes",
  "SPY": "LPO, Black lug nuts",
  "SPZ": "LPO, Black wheel locks",
  "SRI": "Wheels, 20\" (50.8 cm) Black-painted aluminum with Red accents",
  "STI": "LPO, Satin Black rocker moldings",
  "T42": "Spoiler, rear, visible weave carbon fiber",
  "UD7": "Rear Park Assist",
  "UEU": "Forward Collision Alert",
  "UFG": "Rear Cross Traffic Alert",
  "UHS": "Driver Information Center",
  "UKC": "Lane Change Alert",
  "UPG": "Bluetooth for phone",
  "UQA": "Audio system feature, Bose premium 9-speaker system",
  "UQT": "Performance data and video recorder",
  "UV6": "Head-Up Display",
  "UVB": "HD Rear Vision Camera",
  "UVD": "Steering wheel, heated",
  "VAV": "LPO, All-weather floor mats",
  "VDN": "LPO, Indoor vehicle cover",
  "VK3": "License plate bracket, front",
  "VLI": "LPO, All-weather cargo mat",
  "VLN": "LPO, Windscreen",
  "VPO": "LPO, Gray Hash Mark Stripes",
  "VPW": "LPO, Black Metallic Body-Side Spear Stripes",
  "VQL": "LPO, Fuel filler door in Black with visible carbon fiber insert",
  "VRU": "LPO, Outdoor vehicle cover, Gray",
  "VRV": "LPO, Body-color painted splash guards",
  "VTA": "LPO, Black exhaust tip",
  "VTD": "LPO, Ground effects, Carbon Flash Metallic",
  "VTF": "LPO, Embroidered center console lid",
  "VTG": "LPO, White Interior Trim Kit",
  "VTU": "LPO, Fuel filler door in Black with Gloss Black insert",
  "VUP": "Redline Edition graphics",
  "VW9": "LPO, Black SS wheel center caps",
  "VWD": "LPO, Gloss Black wheel center caps with Silver bowtie",
  "W0D": "LPO, Fuel filler door in Black with Red Hot insert",
  "W0E": "LPO, Fuel filler door in Black with Silver Ice Metallic insert",
  "W2D": "LPO, Cargo net",
  "WBL": "Redline Edition",
  "WGK": "LPO, Red Interior Trim Kit",
  "WGT": "LPO, Black Interior Trim Kit",
  "WR1": "Wheels, 20\" (50.8 cm) 5-split spoke polished forged aluminum with Black star center cap",
  "WRS": "RS Package",
  "XLC": "Launch control, custom",
  "Y3W": "Technology Package",
  "Z4B": "Camaro Collector Edition - SS/LT/ZL1 models",
}

module.exports = {
  colorMap,
  intColor,
  seatCode,
  mmc,
  camaroRpo
}
