const rpoDescriptions = {
    "00T":	"Convertible top color, Blue",
    "0ST":  "VAA/Component Rel",
    "19T":	"Convertible top color, Black",
    "1LT":  "Base Equipment Package",
    "1NF":  "VAA/Component",
    "1SE":  "ZL1 Equipment Package",
    "1SZ":  "Option Package Discount",
    "21T":	"Convertible top color, Kalahari",
    "2F5":	"Knee pads, Red",
    "2LT":  "Base Equipment Package",
    "2NF":  "VAA/Components",
    "2SS":  "Base Equipment Package",
    "2ST":  "VAA/Component",
    "3DL":	"Interior trim, carbon fiber instrument panel molding",
    "3F9":	"Seat belt color, Red",
    "3LT":  "Base Equipment Package",
    "4AA":  "Interior Trim, Jet Black",
    "4F2":  "Interior Trim, Jet Black / Kalahari",
    "4F7":  "Interior Trim, Jet Black / Medium Ash Gray",
    "4F9":  "Interior Trim, Jet Black / Ceramic White",
    "4G2":  "Interior Trim, Jet Black / Adrenaline Red",
    "56H":	"LPO, SS 20\" (50.8 cm) 5-spoke gloss Black wheels with Red stripe",
    "56K":	"LPO, SS 20\" (50.8 cm) 5-split spoke polished forged wheels with Black star center cap",
    "56M":	"LPO, SS 20\" (50.8 cm) 5-split spoke machined-face wheels",
    "56R":	"Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear 5-split spoke premium Gray-painted machined-face aluminum",
    "56S":	"Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear bright 5-spoke Silver-painted aluminum",
    "56V":	"Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear 5-spoke Carbon Flash painted aluminum",
    "56W":	"Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear 5-spilt spoke bright Silver-painted aluminum",
    "56Y":	"Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear blade design aluminum",
    "56Z":	"Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear 5-split spoke Black forged aluminum",
    "57S":	"LPO, SS 20\" (50.8 cm) 5-split spoke Satin Black wheels",
    "57V":	"Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear Caliente",
    "57W":	"Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear 5-split spoke polished forged aluminum with Black star center cap",
    "58E":	"Wheels, 20\" x 8.5\" (50.8 cm x 21.6 cm) front and 20\" x 9.5\" (50.8 cm x 24.1 cm) rear Black-painted aluminum with Red accents",
    "5A7":  "Spare Wheel Deletion GM Accessory",
    "5AA":  "Spare Wheel-None",
    "5JW":	"LPO, 20\" (50.8 cm) 5-split spoke polished forged wheels with Black star center cap",
    "5JX":	"LPO, LT 20\" (50.8 cm) 5-split spoke Satin Black wheels",
    "5K2":	"LPO, Decklid blackout decal",
    "5K9":	"Wheels, 20\" (50.8 cm) Caliente",
    "5KP":	"LPO, Illuminated sill plates",
    "5LQ":	"LPO, 6 Piston Front Brake Kit",
    "5V5":	"LPO, Body-color high-wing spoiler",
    "5V6":	"LPO, Black Interior Appearance Package",
    "5VF":	"LPO, Carbon fiber exhaust tip",
    "5VM":	"LPO, Ground Effects Package",
    "5WF":	"LPO, Battery Protection Package",
    "5YN":	"LPO, Carbon Fiber-look shift knob (auto) or Carbon Fiber-look shift knob medallion (manual)",
    "5ZB":	"LPO, Camaro logo wheel center caps",
    "5ZD":	"LPO, Wheel center caps",
    "5ZU":	"LPO, Body-color blade spoiler",
    "5ZV":	"LPO, Satin Black blade spoiler",
    "5ZW":	"LPO, Satin Black wing spoiler",
    "5ZZ":	"LPO, Carbon Flash Metallic blade spoiler",
    "62F":	"LPO, Premium carpeted cargo mat with Camaro logo",
    "62O":	"LPO, Clear CHMSL (Center High Mount Stop Lamp)",
    "6X1":  "COMPONENT FRT LH NON-COMPUTER SEL SUSP",
    "6ZQ":	"LPO, ZL1 1LE SPEC visible carbon fiber spoiler",
    "7X1":  "COMPONENT FRT RH NON-COMPUTER SEL SUSP",
    "8AA":  "COMPONENT RR LH COMPUTER SEL SUSP (8AA)",
    "8AB":  "COMPONENT RR LH COMPUTER SEL SUSP (8AB)",
    "8AT":  "Spring/Suspension - Rear LH (Air Spring)",
    "8BB":  "Component RR LH Computer Sel Susp",
    "8CA":  "Component-Computer Select Susp",
    "8DX":  "COMPONENT RR LH COMPUTER SEL SUSP",
    "8GW":  "Component RR LH",
    "9AA":  "COMPONENT RR RH COMPUTER SEL SUSP (9AA)",
    "9AT":  "Spring/Suspension - Rear LH",
    "9BB":  "Component RR RH Computer Sel Susp",
    "9CA":  "Component RR RH Computer Sel Susp",
    "9DX":  "COMPONENT RR RH COMPUTER SEL SUSP",
    "9GW":  "Component RR RH",
    "9L3":  "Spare Tire - None",
    "A1X":	"1LE Track Performance Package",
    "A1Y":	"SS 1LE Track Performance Package",
    "A1Z":	"ZL1 1LE Extreme Track Performance Package",
    "A45":	"Memory Package",
    "A50":	"Seats, front Sport bucket",
    "A62":	"Seat, rear fixed",
    "A9B":	"Satin Black Appearance Package",
    "AAQ":	"Seat adjuster, front passenger",
    "AJ7":	"Airbags, frontal and side",
    "AJ9":	"Airbags, dual-stage frontal, knee, head and thorax side-impact, driver and front passenger",
    "AKQ":	"Seat adjuster, front passenger, 6-way power",
    "AL0":  "Airbag Sensing System, Front Passenger",
    "AM7":	"Seat, rear, folding",
    "AQ9":	"Seats, front bucket",
    "AQJ":	"Seats, front bucket, RECARO/HIGH performance",
    "AT8":  "Latch System",
    "ATH":	"Keyless Open and Start",
    "AV3":	"Seat adjuster, driver, 8-way power",
    "AXJ":  "Passenger Car",
    "AYG":	"Airbags, dual-stage frontal, thorax side-impact and knee, driver and front passenger, and head curtain side-impact",
    "B0A":  "VEHICLE GM PROD WEEK 19",
    "B0B":  "VEHICLE GM PROD WEEK 20",
    "B0C":  "VEHICLE GM PROD WEEK 21",
    "B0D":  "VEHICLE GM PROD WEEK 22",
    "B0E":  "VEHICLE GM PROD WEEK 23",
    "B0F":  "VEHICLE GM PROD WEEK 24",
    "B0G":  "VEHICLE GM PROD WEEK 25",
    "B0H":  "VEHICLE GM PROD WEEK 26",
    "B0J":  "VEHICLE GM PROD WEEK 27",
    "B0K":  "VEHICLE GM PROD WEEK 28",
    "B0L":  "VEHICLE GM PROD WEEK 29",
    "B0M":  "VEHICLE GM PROD WEEK 30",
    "B0N":  "VEHICLE GM PROD WEEK 31",
    "B0P":  "VEHICLE GM PROD WEEK 32",
    "B0Q":  "VEHICLE GM PROD WEEK 33",
    "B0R":  "VEHICLE GM PROD WEEK 34",
    "B0S":  "VEHICLE GM PROD WEEK 35",
    "B0T":  "VEHICLE GM PROD WEEK 36",
    "B0U":  "VEHICLE GM PROD WEEK 37",
    "B0V":  "VEHICLE GM PROD WEEK 38",
    "B0W":  "VEHICLE GM PROD WEEK 39",
    "B0X":  "VEHICLE GM PROD WEEK 52",
    "B0Y":  "VEHICLE GM PROD WEEK 53",
    "B2E":	"Shock and Steel Special Edition",
    "B34":	"Floor mats, carpeted front",
    "B7G":	"Sill plates, illuminated",
    "B8M":  "VEHICLE GM PROD WEEK 01",
    "B8N":  "VEHICLE GM PROD WEEK 02",
    "B8P":  "VEHICLE GM PROD WEEK 40",
    "B8Q":  "VEHICLE GM PROD WEEK 41",
    "B8R":	"VEHICLE GM PROD WEEK 42",
    "B8S":	"VEHICLE GM PROD WEEK 43",
    "B8T":	"VEHICLE GM PROD WEEK 44",
    "B8U":	"VEHICLE GM PROD WEEK 45",
    "B8V":	"VEHICLE GM PROD WEEK 46",
    "B8W":	"VEHICLE GM PROD WEEK 47",
    "B8X":	"VEHICLE GM PROD WEEK 48",
    "B8Y":	"VEHICLE GM PROD WEEK 49",
    "B8Z":	"VEHICLE GM PROD WEEK 50",
    "B9A":	"VEHICLE GM PROD WEEK 51",
    "B9M":	"Tail lamps, dark tint",
    "BAG":  "Parts Package Export",
    "BCD":	"Performance copper-free brake system",
    "BO3":	"White Pearl Rally Stripes",
    "BO4":	"Black Metallic Rally Stripes",
    "BRD":	"Ceramic White Interior Package",
    "BRJ":	"Adrenaline Red Interior Package",
    "BTV":	"Remote vehicle starter system",
    "C1U":  "Fleet Inventive Enterprise Rent-A-Car",
    "C2U":	"Silver Rally Stripes",
    "C3O":	"Black Rally Stripes",
    "C68":	"Air conditioning, single-zone automatic climate control",
    "C70":	"Lighting, interior spectrum",
    "CF5":	"Sunroof, power",
    "CFW":	"Hood insert, visible Carbon Fiber weave",
    "CG3":	"Emblem, Black Camaro fender badge",
    "CG6":	"Emblem, Black Camaro fender badge with Red outline",
    "CJ2":	"Air conditioning, dual-zone automatic climate control",
    "CM8":	"Convertible top, power-folding",
    "CV3":  "Country Mexico",
    "CZG":  "Control GM of Canada Fleet No. 7",
    "D31":	"Mirror, inside rearview manual day/night",
    "D52":	"Spoiler, rear",
    "D5S":	"Spoiler, rear, blade, Satin Black",
    "D5Z":	"Spoiler, rear, stanchion",
    "D80":	"Spoiler, decklid-mounted lip spoiler",
    "D88":	"1LE Hash Mark Decal",
    "DCP":  "Processing Directions & Connections Service Package",
    "DD1":	"Mirrors, outside heated power-adjustable and driver-side auto-dimming, body-color",
    "DD8":	"Mirror, inside rearview auto-dimming",
    "DG7":	"Mirrors, outside power-adjustable, body-color",
    "DNS":  "Dealer Installed Indicator",
    "DRZ":	"Rear Camera Mirror",
    "DSM":	"Hood wrap, Satin Black",
    "DUU":	"Black Center Stripe",
    "DUV":	"Silver Center Stripe",
    "DVV":	"Black Metallic Center Stripe",
    "DW7":	"White Pearl Center Stripe",
    "DW8":	"Black Metallic Center Stripe",
    "E2B":  "Jet Black with Signet Accents Leather w/ Mini-Perforated Custom Quilted Inserts and Sueded Front Seatbacks",
    "E2D":  "Jet Black with Adrenaline Red Accents Leather w/ Mini-Perforated Custom Quilted Inserts and Sueded Front Seatbacks",
    "E2G":  "Jet Black with Sky Cool Gray Accents Leather w/ Mini-Perforated Custom Quilted Inserts and Sueded Front Seatbacks",
    "EF7":  "Country Code, U.S.A.",
    "F55":	"Magnetic Ride Control",
    "FE2":	"Suspension, Sport",
    "FE3":	"Suspension, Performance",
    "FE4":	"Suspension, Performance",
    "FE9":	"Emissions, Federal requirements",
    "FEA":	"Suspension, Performance",
    "FJW":  "Vehicle Fuel Gasoline",
    "FLT":  "Sales Processing Option",
    "FTF":	"Front splitter",
    "FTJ":	"Front splitter",
    "G16":  "Crush",
    "G1M":  "Blue Velvet Metallic",
    "G7C":  "Red Hot",
    "G7D":  "Bright Yellow",
    "G7E":  "Garnet Red Metallic",
    "G7Q":  "Nightfall Gray Metallic",
    "G80":	"Differential, limited slip",
    "G96":	"Differential, electronic limited-slip",
    "G9K":  "Satin Steel Gray Metallic",
    "GAN":  "Silver Ice Metallic",
    "GAZ":  "Summit White",
    "GB8":  "Mosaic Black Metallic",
    "GBA":  "Black",
    "GCF":  "Vivid Orange Metallic",
    "GCP":  "Nitro Yellow Metallic",
    "GD1":  "Hyper Blue Metallic",
    "GGB":  "Arctic Blue Metallic",
    "GJ0":  "Rally Green Metallic",
    "GJI":  "Shadow Gray Metallic",
    "GJV":  "Riptide Blue Metallic",
    "GKK":  "Riverside Blue Metallic",
    "GKO":  "Shock",
    "GLK":  "Panther Black Metallic",
    "GMO":  "Rapid Blue",
    "GMV":  "Krpton Green",
    "GNT":  "Radiant Red Tintcoat",
    "GNW":  "Panther Black Matte",
    "GSK":  "Wild Cherry Tintcoat",
    "GT4":	"Rear axle, 3.73 ratio",
    "GW6":	"Rear axle, 3.27 ratio",
    "GXD":  "Sharkskin Metallic",
    "H01":  "Kalahari Leather",
    "H0L":  "Sangria with Jet Black Accents Leather w/ Mini-Perforated Inserts",
    "H0M":  "Cinnamon with Jet Black Accents Leather w/ Mini-Perforated Inserts",
    "H0W":  "Jet Black Leather with Red accents",
    "H0Y":  "Jet Black Leather",
    "H13":  "Ceramic White Leather",
    "H16":  "Adrenaline Red Leather",
    "H17":  "Medium Ash Gray Leather",
    "H1T":  "Jet Black Cloth",
    "H1Y":  "Jet Black with Jet Black Accents Leather w/ Mini-Perforated Inserts",
    "H2G":  "Jet Black with Jet Black Accents Inteluxe",
    "H2X":  "Jet Black with Jet Black Accents Leather w/ Mini-Perforated Inserts",
    "H72":  "Medium Ash Gray Cloth",
    "HAV":  "Maple Sugar with Jet Black Accents Leather w/ Mini-Perforated Inserts",
    "HBE":  "Jet Black with Jet Black Accents Leather/Performance Cloth/Sueded Microfiber/Ineluxe and Sueded Front Seatbacks",
    "HBF":  "Natural Tan with Jet Black Accents Leather w/ Mini-Perforated Custom Quilted Inserts and Sueded Front Seatbacks",
    "HEA":  "Jet Black with Jet Black Accents Leather w/ Sueded Front Seatbacks",
    "HEB":  "Sky Cool Gray with Jet Black Accents Leather w/ Sueded Front Seatbacks",
    "HGM":  "Jet Black with Jet Black Accents Leather w/ Mini-Perforated Inserts",
    "HIK":  "Sahara Beige with Jet Black Accents Leather w/ Mini-Perforated Inserts",
    "HIT":  "Sahara Beige with Jet Black Accents Inteluxe",
    "HJC":  "Natural Tan with Jet Black Accents Full Semi-Aniline Leather w/ Mini-Perforated Inserts, Custom Quilting and Carbon Fiber Front Seatbacks",
    "HJD":  "Sky Cool Gray with Jet Black Accents Full Semi-Aniline Leather w/ Mini-Perforated Inserts, Custom Quilting and Carbon Fiber Front Seatbacks",
    "HMC":  "Whisper Beige with Jet Black Accents Inteluxe",
    "HMR":  "Jet Black with Jet Black Accents Full Semi-Aniline Leather w/ Mini-Perforated Inserts, Custom Quilting and Carbon Fiber Front Seatbacks",
    "HNC":  "Whisper Beige with Jet Black Accents Leather w/ Mini-Perforated Inserts",
    "HND":  "Whisper Beige with Jet Black Accents Leather w/ Mini-Perforated Inserts",
    "HRD":	"Rear axle, 2.85 ratio",
    "HRE":	"Rear axle, 2.77 ratio",
    "HXR":  "Jet Black with Jet Black Accents Inteluxe",
    "HZK":  "Sedona Sauvage with Jet Black Accents Semi-Aniline Full Leather w/ Chevron Perforated Inserts",
    "HZQ":  "Jet Black with Jet Black Accents Inteluxe",
    "I20":  "Engineering Year-2020",
    "IOR":	"Audio system, Chevrolet Infotainment 3 system, 7\" diagonal color touchscreen",
    "IOS":	"Audio system, Chevrolet Infotainment 3 Plus system, 8\" diagonal HD color touchscreen",
    "IOT":	"Audio system, Chevrolet Infotainment 3 Premium system with connected Navigation, 8\" diagonal HD color touchscreen",
    "J20":  "Engineering Year 2020",
    "J21":  "Engineering Year 2021",
    "J22":  "Engineering Year 2022",
    "J23":  "Engineering Year 2023",
    "J24":  "Engineering Year 2024",
    "J55":	"Brakes, Brembo 4-piston front, performance, 4-wheel antilock, 4-wheel disc",
    "J6E":	"Calipers, Yellow",
    "J6F":	"Calipers, Red",
    "J6G":	"Brakes, Brembo 4-piston front and rear, performance, 4-wheel antilock, 4-wheel disc",
    "J6H":	"Brakes, Brembo 6-piston front and 4-piston rear, performance",
    "J6L":	"Calipers, Orange",
    "J6M":	"Brakes, Brembo Red, 6-piston front monobloc calipers, 4-piston rear calipers, 2-piece rotors, performance",
    "J71":  "eBrake - Motor on Caliper",
    "J77":  "Brake, Electronic Parking",
    "JF5":	"Pedals, sport alloy",
    "JL9":	"Brakes, 4-wheel antilock, 4-wheel disc",
    "K05":	"Engine block heater",
    "K4C":	"Wireless Charging",
    "KA1":	"Seats, heated driver and front passenger",
    "KB7":	"Paddle-shift manual controls",
    "KC4":	"Cooling, external engine oil cooler",
    "KD1":	"Cooler, transmission oil",
    "KNR":	"Cooler, rear differential",
    "KQV":	"Seats, ventilated driver and front passenger",
    "KR1":  "Refrigerant Air Conditioning",
    "KRV":  "Refrigerant",
    "KS9":	"Shift knob, sueded microfiber-wrapped",
    "KTI":	"Tire inflation kit",
    "LAL":  "Lansing Plant Grand River",
    "LGX":	"Engine, 3.6L V6, DI, VVT",
    "LT1":	"Engine, 6.2L (376 ci) V8 DI",
    "LT4":	"Engine, 6.2L supercharged V8",
    "LTG":	"Engine, 2.0L Turbo, 4-cylinder, SIDI, VVT",
    "M13":  "Transmission, 6-speed manual - TR-3160",
    "M97":  "Brake/Trans Shift Interlock",
    "MAH":  "Marketing Area North America",
    "MBC":  "Marketing Area Canada",
    "MCR":  "Receptable Memory Card",
    "MCX":  "Marketing Area Mexico",
    "MH3":  "Transmission, 6-speed manual - TR-6060",
    "MI1":  "Transmission Auto 10-Speed, 10L60, VAR 1, Gen 1",
    "MI2":  "Transmission, 10-speed automatic",
    "MI3":  "Transmission, 6-speed manual - TR-3160",
    "MI4":  "Transmission Auto 10-Speed, 10L90, VAR 1, Gen 1",
    "MJK":  "Transmission, 6-speed manual - TR-6060",
    "MM6":  "Transmission, 6-speed manual - TR-6060",
    "MN6":	"Transmission, 6-speed manual",
    "MX0":	"Transmission, Automatic",
    "N10":	"Exhaust, dual-outlet stainless-steel",
    "N26":	"Steering wheel, 3-spoke, sueded microfiber-wrapped, flat-bottom",
    "NB8":	"Emissions override, California",
    "NB9":	"Emissions override, state-specific",
    "NC7":	"Emissions override, Federal",
    "NE1":	"Emissions, Connecticut, Delaware, Maine, Maryland, Massachusetts, New Jersey, New York, Oregon, Pennsylvania, Rhode Island, Vermont and Washington state requirements",
    "NE8":  "Emissions",
    "NKC":  "Noise Control System",
    "NKE":  "Noise Control - Electronic Sound Enhancer",
    "NP5":	"Steering wheel, leather-wrapped",
    "NPP":	"Exhaust, dual-mode",
    "NTB":  "Emission System Federal",
    "NUC":  "Emission System-California, ULEV50",
    "NV9":	"Steering, power",
    "OAR":  "Pre-Production Vehicle",
    "P0G":	"GM Commercial Link - 1 year of Service",
    "P0H":	"GM Commercial Link - 2 years of Service",
    "P0I":	"GM Commercial Link - 3 years of Service",
    "P0J":	"OnStar Additional 21 months of OnStar Fleet Safety and Security",
    "P0K":	"OnStar Additional 33 months of OnStar Fleet Safety and Security",
    "P0L":	"OnStar Additional 45 months of OnStar Fleet Safety and Security",
    "P0M":	"OnStar Additional 21 months of OnStar Fleet Driver Remote Access",
    "P0N":	"OnStar Additional 33 months of OnStar Fleet Driver Remote Access",
    "P0O":	"OnStar Additional 45 months of OnStar Fleet Driver Remote Access",
    "P0P":	"OnStar Additional 57 months of OnStar Fleet Driver Remote Access",
    "P0Q":	"OnStar Additional 57 months of OnStar Fleet Safety and Security",
    "P0R":	"OnStar Additional 9 months of OnStar Fleet Driver Remote Access",
    "P0U":	"OnStar Additional 9 months of OnStar Fleet Safety and Security",
    "P0V":	"OnStar Vehicle Insights - 1 year of Service",
    "P0W":	"OnStar Vehicle Insights - 2 years of Service",
    "P0X":	"OnStar Vehicle Insights - 3 years of Service",
    "P0Y":	"OnStar Vehicle Insights - 4 years of Service",
    "P0Z":	"OnStar Vehicle Insights - 5 years of Service",
    "P1R":	"OnStar Additional 9 months of OnStar Fleet Assurance",
    "P1S":	"OnStar Additional 21 months of OnStar Fleet Assurance",
    "P1T":	"OnStar Additional 33 months of OnStar Fleet Assurance",
    "P1U":	"OnStar Additional 45 months of OnStar Fleet Assurance",
    "P3H":	"Bowties, Black, front and rear",
    "PCH":	"LPO, Performance Enthusiast Package with Gray accents",
    "PCI":	"LPO, Performance Enthusiast Package with Red accents",
    "PCJ":	"LPO, Dark Tint Rear Lighting Package",
    "PCK":	"LPO, Black Accent Exterior Package",
    "PCL":	"LPO, Black Wheel Lug Nuts and Locks Package",
    "PCN":	"LPO, Winter/Summer Floor Mats Package",
    "PCR":	"LPO, Satin Black Front Splitter/Side Rockers Package",
    "PCU":	"LPO, 4-Corner Brembo brake upgrade system in Red",
    "PCV":	"LPO, RS/SS Interior Package",
    "PCW":	"LPO, Camaro Logo Premium Carpeted Mats Package",
    "PCX":	"LPO, Camaro Logo Package",
    "PCY":	"LPO, Red Accent Exterior Package",
    "PDB":	"LPO, Winter Protection Package",
    "PDL":	"Design Package 1",
    "PDN":	"Design Package 2",
    "PDP":	"Design Package 3",
    "PDV":	"LPO, Camaro Insignia Package",
    "PDX":	"LPO, ZL1 Protection Package",
    "PDY":	"LPO, Body-Color Spoiler with Wicker Package",
    "PKJ":	"Wheels, 19\" x 11\" (48.3 cm x 27.9 cm) front and 19\" x 12\" (48.3 cm x 30.48 cm) rear low gloss Black-painted forged aluminum",
    "PPW":	"Wireless Apple CarPlay/Wireless Android Auto",
    "PR6":	"SiriusXM, Additional 9 months of the SXM Platinum Plan",
    "PR7":	"SiriusXM, Additional 21 months of the SXM Platinum Plan",
    "PR8":	"SiriusXM, Additional 33 months of the SXM Platinum Plan",
    "PRF":	"3 Years of OnStar Remote Access",
    "Q7F":	"Wheels, 20\" (50.8 cm) blade design aluminum",
    "Q7G":	"Wheels, 20\" (50.8 cm) 5-split spoke Black forged aluminum",
    "R0F":	"Tires, 245/40ZR20 front and 275/35ZR20 rear, blackwall, summer-only",
    "R0G":	"Tires, 285/30R20 front and 305/30R20 rear, blackwall, summer-only",
    "R0H":	"Tires, 245/50R18, blackwall, all-season",
    "R29":	"Tires, 245/40R20, blackwall, all-season",
    "R6F":  "10 Gallon Tank, Natural Gas Vehicle",
    "R6I":  "Buildable Order Confirmation",
    "R6J":  "Ship Thru Code Acknowledgement",
    "R6O":	"Tires, 305/30R19 front and 325/30R19 rear, blackwall, summer-only",
    "R6Z":  "Control Sales Item No. 25",
    "R7E":  "ID-License Plate Bracket Charge",
    "R7K":  "Control Sales Item No. 36",
    "R7V":  "Control Sales Item No. 46",
    "R7W":  "Control Sales Item No. 47",
    "R7Z":	"OnStar Additional 57 months of OnStar Fleet Assurance",
    "R88":	"LPO, Front illuminated and rear non-illuminated bowtie emblems in Black",
    "R8B":  "CONTROL SALES ITEM NO. 52",
    "R8E":  "Gas Guzzler Tax",
    "R8J":  "LGR-ID Camaro Coupe Models",
    "R8S":	"OnStar In-Vehicle Coaching - 1 Year of Service",
    "R8V":	"Not Equipped with Hood Insulator, see dealer for details.",
    "R9C":  "CONTROL SALES ITEM NO. 78",
    "R9L":	"Deleted 3 Years of OnStar Remote Access",
    "R9N":  "VOMS Processing Option",
    "R9Y":	"Fleet Free Maintenance Credit",
    "R9Z":  "Control Sales Item No. 100",
    "REG":	"Wheels, 18\" (45.7 cm) Silver-painted aluminum",
    "RFR":	"OnStar In-Vehicle Coaching - 1 year of Service",
    "RFS":	"OnStar In-Vehicle Coaching - 2 Years of Service",
    "RFT":	"OnStar In-Vehicle Coaching - 3 Years of Service",
    "RFU":	"OnStar In-Vehicle Coaching - 4 Years of Service",
    "RFY":	"OnStar In-Vehicle Coaching - 5 Years of Service",
    "RIK":	"LPO, Black front and rear bowtie emblems",
    "RIN":	"LPO, Camaro logo fender badge",
    "RMH":	"LPO, Front splitter, Carbon Flash Metallic",
    "RNX":	"LPO, Outdoor vehicle cover",
    "RO1":	"LPO, Black lower grille with Silver-painted inserts",
    "RO2":	"LPO, Black lower grille with Gloss Black inserts",
    "RQ9":	"Wheels, 20\" (50.8 cm) 5-split spoke premium Gray-painted, machined-face aluminum",
    "RQA":	"Wheels, 20\" (50.8 cm) Silver-painted aluminum",
    "RSK":	"Wheels, 20\" x 10\" (50.8 cm x 25.4 cm) front and 20\" x 11\" (50.8 cm x 27.9 cm) rear Satin Graphite forged aluminum",
    "RTG":  "Wheels, 20\" x 8.0\", J, Aluminum, Design 1",
    "RTH":	"Wheels, 20\" (50.8 cm) 5-spoke Carbon Flash painted aluminum",
    "RTJ":	"Wheels, 20\" (50.8 cm) 5-spilt spoke bright Silver-painted aluminum",
    "RTQ":	"Wheels, 20\" x 10\" (50.8 cm x 25.4 cm) front and 20\" x 11\" (50.8 cm x 27.9 cm) rear Dark Graphite premium paint, forged aluminum",
    "RVK":	"LPO, Performance air intake",
    "RWH":	"LPO, Indoor vehicle cover",
    "RWJ":	"LPO, Outdoor vehicle cover",
    "RX0":	"LPO, 4 Piston Brembo rear calipers in Red",
    "RXH":	"LPO, Silver RS wheel center caps",
    "RXJ":	"LPO, Silver SS wheel center caps",
    "RY2":	"LPO, Black Metallic Hash Mark Stripes",
    "RZ3":	"LPO, Front splitter",
    "RZB":	"LPO, Black lower grille with Red Hot inserts",
    "S0O":	"LPO, Illuminated footwells",
    "S0U":	"LPO, Black sueded knee pads",
    "S0V":	"LPO, White knee pads",
    "S54":	"LPO, Navigation upgrade kit",
    "SA7":	"LPO, Suede shift knob and boot kit",
    "SB2":	"LPO, Carbon Flash Metallic wing spoiler",
    "SB3":	"LPO, ZL1 SPEC rear spoiler, body-color",
    "SB7":	"LPO, Red Spider Stripes",
    "SB9":	"LPO, Satin Black Spider Stripes",
    "SBF":  "Safety Belts",
    "SC1":	"LPO, Sway bar suspension upgrade system",
    "SCG":	"LPO, 6.2L Strut tower brace in Black",
    "SCJ":	"LPO, Suspension Handling Package, 1LE Track Pack - V8",
    "SCY":	"LPO, Dark finish tail lamps",
    "SF8":	"LPO, Silver Body-Side Spear Stripes",
    "SF9":	"LPO, Blue Hash Mark Stripes",
    "SFA":	"LPO, Red Stinger Stripe",
    "SFC":	"LPO, White Pearl Hash Mark Stripes",
    "SFE":	"LPO, Wheel locks",
    "SFZ":	"LPO, Camaro fender badge, Black",
    "SG3":	"LPO, Lowering suspension upgrade system",
    "SGE":	"Wheels, 18\" (45.7 cm) 5-split spoke Silver-painted aluminum",
    "SH1":	"LPO, Embroidered center console lid with Camaro badge",
    "SH2":	"LPO, Embroidered center console lid",
    "SHL":	"LPO, 20\" (50.8 cm) 5-spoke gloss Black wheels with Red outline stripe",
    "SHQ":	"LPO, Silver Hash Mark Stripes",
    "SHS":	"LPO, Satin Black Hood Stripe with Silver Ice Metallic Hash Mark",
    "SHT":	"Spoiler stripe",
    "SHU":	"LPO, Satin Black Hood Stripe with Red Hot Hash Mark",
    "SIA":	"LPO, Wicker bill",
    "SIB":	"LPO, Interior spectrum lighting, Dark Night",
    "SIC":	"LPO, Interior spectrum lighting, Red Day, Satin Red and Gloss Red pattern finish",
    "SJ8":	"LPO, Interior spectrum lighting, Structura",
    "SKW":	"LPO, 20\" (50.8 cm) 5-split spoke machined-face wheels",
    "SL1":	"LPO, Indoor vehicle cover",
    "SL2":	"LPO, Front splitter",
    "SLL":  "Sold Orders",
    "SLM":  "Stock Orders",
    "SLN":	"LPO, Strut tower brace",
    "SNB":	"LPO, Silver Spider Stripes",
    "SNC":	"LPO, White Pearl Spider Stripes",
    "SNE":	"LPO, Silver Stinger Stripe",
    "SNG":	"LPO, Red Hash Mark Stripes",
    "SNH":	"LPO, White Pearl Body-Side Spear Stripes",
    "SNJ":	"LPO, Satin Black Stinger Stripe",
    "SNM":	"LPO, White Pearl Stinger Stripe",
    "SNP":	"LPO, Red Body-Side Spear Stripes",
    "SNQ":	"LPO, Gray Body-Side Spear Stripes",
    "SNS":	"LPO, Blue Body-Side Spear Stripes",
    "SPY":	"LPO, Black lug nuts",
    "SPZ":	"LPO, Black wheel locks",
    "SRI":	"Wheels, 20\" (50.8 cm) Black-painted aluminum with Red accents",
    "STI":	"LPO, Satin Black rocker moldings",
    "T3S":  "Daytime Running Lamps",
    "T42":	"Spoiler, rear, visible weave carbon fiber",
    "T4F":  "Headlamps, High Intensity Discharge",
    "T4L":  "Headlamps LED",
    "T61":  "Lamp System Daytime Running",
    "TD2":  "Ship Thru - Ground Effects",
    "TDM":	"Teen Driver",
    "U19":  "Speedometer, Instrument, Kilometers Per Hour",
    "U2K":	"SiriusXM",
    "U77":	"Antenna, integral rear window",
    "U80":  "Compass Display",
    "UB3":	"Antenna, AM/FM",
    "UD7":	"Rear Park Assist",
    "UDD":	"Driver Information Center, color display",
    "UE1":	"OnStar and Chevrolet connected services capable",
    "UEU":	"Forward Collision Alert",
    "UFG":	"Rear Cross Traffic Alert",
    "UHS":	"Driver Information Center",
    "UJM":  "Tire Pressure Monitor System",
    "UKC":	"Lane Change Alert",
    "UMN":	"Speedometer, miles/kilometers",
    "UPG":	"Bluetooth for phone",
    "UQ3":	"Audio system feature, 6-speaker system",
    "UQA":	"Audio system feature, Bose premium",
    "UQT":	"Performance data and video recorder",
    "UST":  "Audio system feature, USB port",
    "UV6":	"Head-Up Display",
    "UVB":	"HD Rear Vision Camera",
    "UVD":	"Steering wheel, heated",
    "V03":	"Cooling system, extra capacity",
    "V18":	"Cooler, engine coolant",
    "V8C":  "Vehicle Statement Mexico",
    "V8D":  "Vehicle Statement US",
    "V8E":  "Vehicle Statement Canada",
    "VAV":	"LPO, All-weather floor mats",
    "VDN":	"LPO, Indoor vehicle cover",
    "VEB":	"LPO, Sport pedals kit",
    "VGS":	"LPO, Outdoor vehicle cover, Gray, ZL1 logo",
    "VK3":	"License plate bracket, front",
    "VLI":	"LPO, All-weather cargo mat",
    "VLN":	"LPO, Windscreen",
    "VPO":	"LPO, Gray Hash Mark Stripes",
    "VPW":	"LPO, Black Metallic Body-Side Spear Stripes",
    "VQG":	"LPO, Weather Protection Package",
    "VQL":	"LPO, Fuel filler door in Black with visible carbon fiber insert",
    "VRG":  "VAA/Component Rel Cockpit",
    "VRH":  "VAA/Component Rel Steering Column",
    "VRJ":  "VAA/Component Rel Powertrain Dress",
    "VRK":  "VAA/Component Rel Roof Trim",
    "VRL":  "VAA/Component Rel Front Horizontal Suspension",
    "VRM":  "VAA/Component Rel Front Vertical Suspension",
    "VRN":  "VAA/Component Rel Rear Suspension",
    "VRR":  "Value Added ASM Tires & Wheels",
    "VRU":	"LPO, Outdoor vehicle cover, Gray",
    "VRV":	"LPO, Body-color painted splash guards",
    "VT7":  "Owners Manual",
    "VTA":	"LPO, Black exhaust tip",
    "VTD":	"LPO, Ground effects, Carbon Flash Metallic",
    "VTF":	"LPO, Embroidered center console lid",
    "VTG":	"LPO, White Interior Trim Kit",
    "VTU":	"LPO, Fuel filler door in Black with Gloss Black insert",
    "VUP":	"Redline Edition graphics",
    "VV4":	"Wi-Fi Hotspot capable",
    "VW9":	"LPO, Black SS wheel center caps",
    "VWD":	"LPO, Gloss Black wheel center caps with Silver bowtie",
    "VY7":	"Shift knob, leather-wrapped",
    "VYV":	"LPO, Short",
    "VYW":	"LPO, Floor mats, premium carpeted",
    "VYX":	"LPO, Painted engine cover",
    "W0D":	"LPO, Fuel filler door in Black with Red Hot insert",
    "W0E":	"LPO, Fuel filler door in Black with Silver Ice Metallic insert",
    "W1V":	"LPO, Floor mats, premium carpeted",
    "W2D":	"LPO, Cargo net",
    "WBL":	"Redline Edition",
    "WGK":	"LPO, Red Interior Trim Kit",
    "WGL":	"LPO, Kalahari knee pads",
    "WGT":	"LPO, Black Interior Trim Kit",
    "WHA":	"LPO, Red knee pads",
    "WL2":	"LPO, Floor mats, premium carpeted with 1LE performance logo",
    "WL3":	"LPO, Premium carpeted floor mats",
    "WML":  "VIN Model Year 2020",
    "WMU":  "VIN MODEL YEAR-2021",
    "WMW":  "VIN Model Year 2022",
    "WMY":  "VIN Model Year 2024",
    "WR1":	"Wheels, 20\" (50.8 cm) 5-split spoke polished forged aluminum with Black star center cap",
    "WRS":	"RS Package",
    "X56":	"Garage 56 Edition",
    "XL8":  "Frequency Rating",
    "XLC":	"Launch control, custom",
    "Y3W":	"Technology Package",
    "Y4Q":	"Heavy-Duty Cooling and Brake Package",
    "YF5":	"Emissions, California state requirements",
    "YM8":  "Identification - LPO",
    "Z49":  "Mandatory Canadian Base Equipment Modifications (Canadian)",
    "Z4B":	"Camaro Collector Edition",
    "ZL1":  "Merchandised Package Special Performance",
    "ZN2":	"Convenience and Lighting Package"
};

function getRPODescription(code) {
    return rpoDescriptions[code] || "N/A";
}